export interface HanziEntry {
  hanzi: string
  pinyin: string
  meaning: string
}

interface HanziSuggestionMetadata {
  pinyin: string
  groupOrder: number
  order: number
}

interface HanziSourceEntry extends HanziEntry {
  suggestions?: HanziSuggestionMetadata[]
}

const HANZI_ENTRIES_BY_ID = {
  "一": { hanzi: "一", pinyin: "yī", meaning: "um", suggestions: [{"pinyin":"yi","groupOrder":41,"order":0}] },
  "二": { hanzi: "二", pinyin: "èr", meaning: "dois", suggestions: [{"pinyin":"er","groupOrder":42,"order":0}] },
  "三": { hanzi: "三", pinyin: "sān", meaning: "três", suggestions: [{"pinyin":"san","groupOrder":43,"order":0}] },
  "四": { hanzi: "四", pinyin: "sì", meaning: "quatro", suggestions: [{"pinyin":"si","groupOrder":44,"order":0}] },
  "五": { hanzi: "五", pinyin: "wǔ", meaning: "cinco", suggestions: [{"pinyin":"wu","groupOrder":45,"order":0}] },
  "六": { hanzi: "六", pinyin: "liù", meaning: "seis", suggestions: [{"pinyin":"liu","groupOrder":46,"order":0}] },
  "七": { hanzi: "七", pinyin: "qī", meaning: "sete", suggestions: [{"pinyin":"qi","groupOrder":47,"order":0}] },
  "八": { hanzi: "八", pinyin: "bā", meaning: "oito", suggestions: [{"pinyin":"ba","groupOrder":48,"order":0}] },
  "九": { hanzi: "九", pinyin: "jiǔ", meaning: "nove", suggestions: [{"pinyin":"jiu","groupOrder":32,"order":1}] },
  "十": { hanzi: "十", pinyin: "shí", meaning: "dez", suggestions: [{"pinyin":"shi","groupOrder":3,"order":1}] },
  "人": { hanzi: "人", pinyin: "rén", meaning: "pessoa", suggestions: [{"pinyin":"ren","groupOrder":4,"order":0}] },
  "大": { hanzi: "大", pinyin: "dà", meaning: "grande", suggestions: [{"pinyin":"da","groupOrder":29,"order":0}] },
  "口": { hanzi: "口", pinyin: "kǒu", meaning: "boca; entrada" },
  "中": { hanzi: "中", pinyin: "zhōng", meaning: "meio; médio; centro" },
  "小": { hanzi: "小", pinyin: "xiǎo", meaning: "pequeno", suggestions: [{"pinyin":"xiao","groupOrder":30,"order":0}] },
  "上": { hanzi: "上", pinyin: "shàng", meaning: "cima; acima; começar; início" },
  "下": { hanzi: "下", pinyin: "xià", meaning: "baixo; abaixo; finalizar" },
  "国": { hanzi: "国", pinyin: "guó", meaning: "país", suggestions: [{"pinyin":"guo","groupOrder":71,"order":0}] },
  "学": { hanzi: "学", pinyin: "xué", meaning: "estudar", suggestions: [{"pinyin":"xue","groupOrder":56,"order":0}] },
  "习": { hanzi: "习", pinyin: "xí", meaning: "praticar; morfema de ligação" },
  "汉": { hanzi: "汉", pinyin: "hàn", meaning: "dinastia Han; povo chinês" },
  "语": { hanzi: "语", pinyin: "yǔ", meaning: "linguagem, idioma" },
  "文": { hanzi: "文", pinyin: "wén", meaning: "língua escrita, civilização, cultura" },
  "写": { hanzi: "写", pinyin: "xiě", meaning: "escrever" },
  "字": { hanzi: "字", pinyin: "zì", meaning: "caractere, letra, nome" },
  "女": { hanzi: "女", pinyin: "nǚ", meaning: "mulher; feminino" },
  "子": { hanzi: "子", pinyin: "zǐ", meaning: "filho; criança" },
  "好": { hanzi: "好", pinyin: "hǎo", meaning: "bom; bem; ok" },
  "水": { hanzi: "水", pinyin: "shuǐ", meaning: "água" },
  "门": { hanzi: "门", pinyin: "mén", meaning: "porta", suggestions: [{"pinyin":"men","groupOrder":7,"order":1}] },
  "王": { hanzi: "王", pinyin: "wáng", meaning: "rei" },
  "日": { hanzi: "日", pinyin: "rì", meaning: "sol, dia" },
  "月": { hanzi: "月", pinyin: "yuè", meaning: "lua, mês" },
  "木": { hanzi: "木", pinyin: "mù", meaning: "árvore, madeira" },
  "马": { hanzi: "马", pinyin: "mǎ", meaning: "cavalo", suggestions: [{"pinyin":"ma","groupOrder":49,"order":1}] },
  "田": { hanzi: "田", pinyin: "tián", meaning: "campo para cultivo" },
  "天": { hanzi: "天", pinyin: "tiān", meaning: "céu, dia" },
  "明": { hanzi: "明", pinyin: "míng", meaning: "brilhante, amanhã" },
  "林": { hanzi: "林", pinyin: "lín", meaning: "bosque" },
  "休": { hanzi: "休", pinyin: "xiū", meaning: "descansar" },
  "男": { hanzi: "男", pinyin: "nán", meaning: "homem" },
  "妈": { hanzi: "妈", pinyin: "mā", meaning: "mãe, mamãe" },
  "河": { hanzi: "河", pinyin: "hé", meaning: "rio", suggestions: [{"pinyin":"he","groupOrder":20,"order":2}] },
  "们": { hanzi: "们", pinyin: "men", meaning: "partícula de plural" },
  "问": { hanzi: "问", pinyin: "wèn", meaning: "perguntar", suggestions: [{"pinyin":"wen","groupOrder":72,"order":0}] },
  "您": { hanzi: "您", pinyin: "nín", meaning: "você (formal, respeitoso)" },
  "贵": { hanzi: "贵", pinyin: "guì", meaning: "caro, valioso, honrado" },
  "姓": { hanzi: "姓", pinyin: "xìng", meaning: "sobrenome, sobrenomear" },
  "我": { hanzi: "我", pinyin: "wǒ", meaning: "eu", suggestions: [{"pinyin":"wo","groupOrder":2,"order":0}] },
  "是": { hanzi: "是", pinyin: "shì", meaning: "ser (verbo)" },
  "呢": { hanzi: "呢", pinyin: "ne", meaning: "partícula de pergunta (e...?)" },
  "吗": { hanzi: "吗", pinyin: "ma", meaning: "partícula de pergunta (s/n)" },
  "不": { hanzi: "不", pinyin: "bù", meaning: "não (adv. Negação)" },
  "他": { hanzi: "他", pinyin: "tā", meaning: "ele", suggestions: [{"pinyin":"ta","groupOrder":6,"order":0}] },
  "她": { hanzi: "她", pinyin: "tā", meaning: "ela", suggestions: [{"pinyin":"ta","groupOrder":6,"order":1}] },
  "你": { hanzi: "你", pinyin: "nǐ", meaning: "você (informal)" },
  "老": { hanzi: "老", pinyin: "lǎo", meaning: "velho, idoso, experiente" },
  "师": { hanzi: "师", pinyin: "shī", meaning: "mestre, professor" },
  "什": { hanzi: "什", pinyin: "shén", meaning: "o que?" },
  "么": { hanzi: "么", pinyin: "me", meaning: "sufixo, morfema" },
  "名": { hanzi: "名", pinyin: "míng", meaning: "nome", suggestions: [{"pinyin":"ming","groupOrder":66,"order":0}] },
  "叫": { hanzi: "叫", pinyin: "jiào", meaning: "chamar, chamar-se" },
  "哪": { hanzi: "哪", pinyin: "nǎ", meaning: "onde; qual" },
  "说": { hanzi: "说", pinyin: "shuō", meaning: "falar", suggestions: [{"pinyin":"shuo","groupOrder":15,"order":0}] },
  "也": { hanzi: "也", pinyin: "yě", meaning: "também" },
  "都": { hanzi: "都", pinyin: "dōu", meaning: "todos, ambos" },
  "只": { hanzi: "只", pinyin: "zhǐ", meaning: "só, somente" },
  "还是": { hanzi: "还是", pinyin: "háishi", meaning: "ou" },
  "很": { hanzi: "很", pinyin: "hěn", meaning: "muito" },
  "高": { hanzi: "高", pinyin: "gāo", meaning: "alto", suggestions: [{"pinyin":"gao","groupOrder":33,"order":0}] },
  "兴": { hanzi: "兴", pinyin: "xìng", meaning: "animado, interessado" },
  "认": { hanzi: "认", pinyin: "rèn", meaning: "reconhecer; saber" },
  "识": { hanzi: "识", pinyin: "shí", meaning: "conhecimento; saber" },
  "在": { hanzi: "在", pinyin: "zài", meaning: "estar, ficar (em)" },
  "工": { hanzi: "工", pinyin: "gōng", meaning: "trabalho", suggestions: [{"pinyin":"gong","groupOrder":65,"order":0}] },
  "作": { hanzi: "作", pinyin: "zuò", meaning: "fazer, trabalho" },
  "司": { hanzi: "司", pinyin: "sī", meaning: "administrar; empresa" },
  "进": { hanzi: "进", pinyin: "jìn", meaning: "entrar" },
  "出": { hanzi: "出", pinyin: "chū", meaning: "sair" },
  "系": { hanzi: "系", pinyin: "xì", meaning: "departamento (universitário)" },
  "可": { hanzi: "可", pinyin: "kě", meaning: "poder" },
  "以": { hanzi: "以", pinyin: "yǐ", meaning: "por meio de; usar como" },
  "电": { hanzi: "电", pinyin: "diàn", meaning: "eletricidade", suggestions: [{"pinyin":"dian","groupOrder":18,"order":1}] },
  "打": { hanzi: "打", pinyin: "dǎ", meaning: "(v.) bater" },
  "话": { hanzi: "话", pinyin: "huà", meaning: "fala; dialeto" },
  "和": { hanzi: "和", pinyin: "hé", meaning: "(prep.) e" },
  "号": { hanzi: "号", pinyin: "hǎo", meaning: "número; dia (informal)" },
  "码": { hanzi: "码", pinyin: "mǎ", meaning: "número; código; senha" },
  "零": { hanzi: "零", pinyin: "líng", meaning: "número 0" },
  "发": { hanzi: "发", pinyin: "fā", meaning: "(v.) enviar por meio eletrônico" },
  "邮": { hanzi: "邮", pinyin: "yóu", meaning: "correio" },
  "件": { hanzi: "件", pinyin: "jiàn", meaning: "item" },
  "给": { hanzi: "给", pinyin: "gěi", meaning: "(v.) dar; (prep.) para" },
  "院": { hanzi: "院", pinyin: "yuàn", meaning: "pátio, instituição" },
  "怎": { hanzi: "怎", pinyin: "zěn", meaning: "como" },
  "样": { hanzi: "样", pinyin: "yàng", meaning: "aparência, tipo" },
  "漂": { hanzi: "漂", pinyin: "piào", meaning: "bonito (parte de 漂亮)" },
  "亮": { hanzi: "亮", pinyin: "liàng", meaning: "brilhante (parte de 漂亮)" },
  "喜": { hanzi: "喜", pinyin: "xǐ", meaning: "gostar, alegria" },
  "这": { hanzi: "这", pinyin: "zhè", meaning: "este", suggestions: [{"pinyin":"zhe","groupOrder":8,"order":0}] },
  "朋": { hanzi: "朋", pinyin: "péng", meaning: "amigo (parte de 朋友)" },
  "友": { hanzi: "友", pinyin: "yǒu", meaning: "amigo", suggestions: [{"pinyin":"you","groupOrder":22,"order":2}] },
  "请": { hanzi: "请", pinyin: "qǐng", meaning: "por favor; convidar" },
  "坐": { hanzi: "坐", pinyin: "zuò", meaning: "sentar", suggestions: [{"pinyin":"zuo","groupOrder":21,"order":1}] },
  "谢": { hanzi: "谢", pinyin: "xiè", meaning: "agradecer" },
  "喝": { hanzi: "喝", pinyin: "hē", meaning: "beber", suggestions: [{"pinyin":"he","groupOrder":20,"order":0}] },
  "茶": { hanzi: "茶", pinyin: "chá", meaning: "chá" },
  "儿": { hanzi: "儿", pinyin: "ér", meaning: "filho, sufixo diminutivo" },
  "里": { hanzi: "里", pinyin: "lǐ", meaning: "dentro, quilômetro" },
  "欢": { hanzi: "欢", pinyin: "huān", meaning: "alegre, feliz" },
  "那": { hanzi: "那", pinyin: "nà", meaning: "aquele" },
  "地方": { hanzi: "地方", pinyin: "dìfāng", meaning: "lugar, local, sítio" },
  "个": { hanzi: "个", pinyin: "gè", meaning: "classificador" },
  "这儿": { hanzi: "这儿", pinyin: "zhèr", meaning: "aqui (também 这里 zhèlǐ)" },
  "家": { hanzi: "家", pinyin: "jiā", meaning: "família; casa" },
  "有": { hanzi: "有", pinyin: "yǒu", meaning: "ter, haver" },
  "几": { hanzi: "几", pinyin: "jǐ", meaning: "quantos, quantas" },
  "口_2": { hanzi: "口", pinyin: "kǒu", meaning: "classificador para pessoas" },
  "爸爸": { hanzi: "爸爸", pinyin: "bàba", meaning: "pai" },
  "妈妈": { hanzi: "妈妈", pinyin: "māma", meaning: "mãe" },
  "和_2": { hanzi: "和", pinyin: "hé", meaning: "e", suggestions: [{"pinyin":"he","groupOrder":20,"order":1}] },
  "太太": { hanzi: "太太", pinyin: "tàitai", meaning: "esposa, mulher" },
  "孩子": { hanzi: "孩子", pinyin: "háizi", meaning: "criança; filho" },
  "男孩儿": { hanzi: "男孩儿", pinyin: "nánháir", meaning: "menino, rapaz" },
  "女孩儿": { hanzi: "女孩儿", pinyin: "nǚháir", meaning: "menina, rapariga" },
  "多大": { hanzi: "多大", pinyin: "duō dà", meaning: "quantos anos" },
  "两": { hanzi: "两", pinyin: "liǎng", meaning: "dois" },
  "岁": { hanzi: "岁", pinyin: "suì", meaning: "anos de idade" },
  "可爱": { hanzi: "可爱", pinyin: "kě'ài", meaning: "querido" },
  "吧": { hanzi: "吧", pinyin: "ba", meaning: "partícula" },
  "学校": { hanzi: "学校", pinyin: "xuéxiào", meaning: "escola, instituição de ensino" },
  "多少": { hanzi: "多少", pinyin: "duōshao", meaning: "quanto(s)" },
  "学生": { hanzi: "学生", pinyin: "xuéshēng", meaning: "aluno" },
  "想": { hanzi: "想", pinyin: "xiǎng", meaning: "pensar", suggestions: [{"pinyin":"xiang","groupOrder":16,"order":0}] },
  "大概": { hanzi: "大概", pinyin: "dàgài", meaning: "aproximadamente, por volta de" },
  "万": { hanzi: "万", pinyin: "wàn", meaning: "dez mil" },
  "没有": { hanzi: "没有", pinyin: "méiyǒu", meaning: "não há" },
  "多": { hanzi: "多", pinyin: "duō", meaning: "muito", suggestions: [{"pinyin":"duo","groupOrder":27,"order":0}] },
  "千": { hanzi: "千", pinyin: "qiān", meaning: "mil" },
  "去": { hanzi: "去", pinyin: "qù", meaning: "ir", suggestions: [{"pinyin":"qu","groupOrder":13,"order":0}] },
  "为什么": { hanzi: "为什么", pinyin: "wèishénme", meaning: "por quê?" },
  "为": { hanzi: "为", pinyin: "wèi", meaning: "para" },
  "分公司": { hanzi: "分公司", pinyin: "fēn gōngsī", meaning: "sucursal/filial de companhia" },
  "老板": { hanzi: "老板", pinyin: "lǎobǎn", meaning: "patrão" },
  "让": { hanzi: "让", pinyin: "ràng", meaning: "deixar, permitir" },
  "那儿": { hanzi: "那儿", pinyin: "nàr", meaning: "lá, ali (também 那里 nàlǐ)" },
  "百": { hanzi: "百", pinyin: "bǎi", meaning: "cem, cento" },
  "少": { hanzi: "少", pinyin: "shǎo", meaning: "pouco", suggestions: [{"pinyin":"shao","groupOrder":28,"order":0}] },
  "因为": { hanzi: "因为", pinyin: "yīnwèi", meaning: "porque" },
  "地图": { hanzi: "地图", pinyin: "dìtú", meaning: "mapa" },
  "张": { hanzi: "张", pinyin: "zhāng", meaning: "classificador para folhas de papel, mapas etc." },
  "中文": { hanzi: "中文", pinyin: "Zhōngwén", meaning: "língua chinesa, chinês" },
  "葡萄牙文": { hanzi: "葡萄牙文", pinyin: "Pútáoyáwén", meaning: "língua portuguesa, português" },
  "看": { hanzi: "看", pinyin: "kàn", meaning: "ver, olhar" },
  "一下": { hanzi: "一下", pinyin: "yíxià", meaning: "um pouco; por um momento" },
  "行": { hanzi: "行", pinyin: "xíng", meaning: "claro que sim; está bem" },
  "要": { hanzi: "要", pinyin: "yào", meaning: "querer, precisar" },
  "给_2": { hanzi: "给", pinyin: "gěi", meaning: "dar" },
  "干": { hanzi: "干", pinyin: "gān", meaning: "fazer" },
  "是的": { hanzi: "是的", pinyin: "shì de", meaning: "sim" },
  "玩儿": { hanzi: "玩儿", pinyin: "wánr", meaning: "fazer uma viagem a; divertir-se" },
  "知道": { hanzi: "知道", pinyin: "zhīdao", meaning: "conhecer; saber" },
  "比较": { hanzi: "比较", pinyin: "bǐjiào", meaning: "comparativamente" },
  "真": { hanzi: "真", pinyin: "zhēn", meaning: "que... tão!; realmente" },
  "有意思": { hanzi: "有意思", pinyin: "yǒu yìsi", meaning: "interessante" },
  "意思": { hanzi: "意思", pinyin: "yìsi", meaning: "interesse" },
  "龙": { hanzi: "龙", pinyin: "lóng", meaning: "dragão" },
  "山": { hanzi: "山", pinyin: "shān", meaning: "montanha, monte" },
  "词典": { hanzi: "词典", pinyin: "cídiǎn", meaning: "dicionário" },
  "汉葡词典": { hanzi: "汉葡词典", pinyin: "Hàn-Pú cídiǎn", meaning: "dicionário chinês-português" },
  "葡汉词典": { hanzi: "葡汉词典", pinyin: "Pú-Hàn cídiǎn", meaning: "dicionário português-chinês" },
  "本": { hanzi: "本", pinyin: "běn", meaning: "classificador para livros" },
  "谁": { hanzi: "谁", pinyin: "shéi / shuí", meaning: "quem" },
  "请问": { hanzi: "请问", pinyin: "qǐng wèn", meaning: "desculpe; para perguntar algo" },
  "对": { hanzi: "对", pinyin: "duì", meaning: "correto, sim" },
  "非常": { hanzi: "非常", pinyin: "fēicháng", meaning: "muito" },
  "有用": { hanzi: "有用", pinyin: "yǒuyòng", meaning: "útil" },
  "能": { hanzi: "能", pinyin: "néng", meaning: "poder" },
  "用": { hanzi: "用", pinyin: "yòng", meaning: "usar" },
  "当然": { hanzi: "当然", pinyin: "dāngrán", meaning: "certamente, com certeza" },
  "书": { hanzi: "书", pinyin: "shū", meaning: "livro", suggestions: [{"pinyin":"shu","groupOrder":63,"order":0}] },
  "本子": { hanzi: "本子", pinyin: "běnzi", meaning: "caderno" },
  "笔": { hanzi: "笔", pinyin: "bǐ", meaning: "caneta, lápis" },
  "支": { hanzi: "支", pinyin: "zhī", meaning: "classificador para caneta, lápis etc." },
  "教室": { hanzi: "教室", pinyin: "jiàoshì", meaning: "sala de aula" },
  "上课": { hanzi: "上课", pinyin: "shàng kè", meaning: "ter aulas" },
  "小姐": { hanzi: "小姐", pinyin: "xiǎojiě", meaning: "senhorita; empregada" },
  "会": { hanzi: "会", pinyin: "huì", meaning: "saber" },
  "一点儿": { hanzi: "一点儿", pinyin: "yìdiǎnr", meaning: "um pouco" },
  "先生": { hanzi: "先生", pinyin: "xiānsheng", meaning: "senhor" },
  "买": { hanzi: "买", pinyin: "mǎi", meaning: "comprar" },
  "件_2": { hanzi: "件", pinyin: "jiàn", meaning: "classificador para roupa" },
  "衬衫": { hanzi: "衬衫", pinyin: "chènshān", meaning: "camisa" },
  "白": { hanzi: "白", pinyin: "bái", meaning: "branco", suggestions: [{"pinyin":"bai","groupOrder":36,"order":0}] },
  "钱": { hanzi: "钱", pinyin: "qián", meaning: "dinheiro" },
  "块": { hanzi: "块", pinyin: "kuài", meaning: "unidade de Renminbi (元 yuán)" },
  "太": { hanzi: "太", pinyin: "tài", meaning: "excessivamente, demais (太……了 = tão...!; 不太…… = não muito...)" },
  "贵_2": { hanzi: "贵", pinyin: "guì", meaning: "caro" },
  "红": { hanzi: "红", pinyin: "hóng", meaning: "vermelho", suggestions: [{"pinyin":"hong","groupOrder":37,"order":0}] },
  "便宜": { hanzi: "便宜", pinyin: "piányi", meaning: "barato" },
  "还": { hanzi: "还", pinyin: "hái", meaning: "ainda; também" },
  "条": { hanzi: "条", pinyin: "tiáo", meaning: "classificador para calças, saia, rua, rio, peixe etc." },
  "裤子": { hanzi: "裤子", pinyin: "kùzi", meaning: "calças" },
  "试": { hanzi: "试", pinyin: "shì", meaning: "experimentar, provar" },
  "那_2": { hanzi: "那", pinyin: "nà", meaning: "nessa situação, nesse caso" },
  "来": { hanzi: "来", pinyin: "lái", meaning: "vir", suggestions: [{"pinyin":"lai","groupOrder":12,"order":0}] },
  "饭店": { hanzi: "饭店", pinyin: "fàndiàn", meaning: "restaurante" },
  "最": { hanzi: "最", pinyin: "zuì", meaning: "o mais" },
  "好吃": { hanzi: "好吃", pinyin: "hǎochī", meaning: "delicioso, saboroso" },
  "菜": { hanzi: "菜", pinyin: "cài", meaning: "prato" },
  "糖醋鱼": { hanzi: "糖醋鱼", pinyin: "tángcùyú", meaning: "peixe agridoce" },
  "糖": { hanzi: "糖", pinyin: "táng", meaning: "açúcar" },
  "醋": { hanzi: "醋", pinyin: "cù", meaning: "vinagre" },
  "鱼": { hanzi: "鱼", pinyin: "yú", meaning: "peixe" },
  "吃": { hanzi: "吃", pinyin: "chī", meaning: "comer", suggestions: [{"pinyin":"chi","groupOrder":19,"order":0}] },
  "辣": { hanzi: "辣", pinyin: "là", meaning: "picante" },
  "酸辣汤": { hanzi: "酸辣汤", pinyin: "suānlàtāng", meaning: "sopa avinagrada e picante" },
  "酸": { hanzi: "酸", pinyin: "suān", meaning: "ácido, avinagrado" },
  "汤": { hanzi: "汤", pinyin: "tāng", meaning: "sopa, caldo" },
  "牛肉": { hanzi: "牛肉", pinyin: "niúròu", meaning: "carne de vaca" },
  "牛": { hanzi: "牛", pinyin: "niú", meaning: "boi, vaca" },
  "肉": { hanzi: "肉", pinyin: "ròu", meaning: "carne" },
  "红烧": { hanzi: "红烧", pinyin: "hóngshāo", meaning: "guisado em molho de soja" },
  "米饭": { hanzi: "米饭", pinyin: "mǐfàn", meaning: "arroz cozido" },
  "水饺": { hanzi: "水饺", pinyin: "shuǐjiǎo", meaning: "ravióis chineses (também 饺子 jiǎozi)" },
  "瓶": { hanzi: "瓶", pinyin: "píng", meaning: "garrafa" },
  "啤酒": { hanzi: "啤酒", pinyin: "píjiǔ", meaning: "cerveja" },
  "等": { hanzi: "等", pinyin: "děng", meaning: "esperar" },
  "东西": { hanzi: "东西", pinyin: "dōngxi", meaning: "coisa" },
  "买东西": { hanzi: "买东西", pinyin: "mǎi dōngxi", meaning: "fazer compras" },
  "商店": { hanzi: "商店", pinyin: "shāngdiàn", meaning: "loja" },
  "卖": { hanzi: "卖", pinyin: "mài", meaning: "vender" },
  "衣服": { hanzi: "衣服", pinyin: "yīfu", meaning: "roupa, vestuário" },
  "你_2": { hanzi: "你", pinyin: "nǐ", meaning: "você", suggestions: [{"pinyin":"ni","groupOrder":0,"order":0}] },
  "好_2": { hanzi: "好", pinyin: "hǎo", meaning: "bom, bem" },
  "是_2": { hanzi: "是", pinyin: "shì", meaning: "ser", suggestions: [{"pinyin":"shi","groupOrder":3,"order":0}] },
  "的": { hanzi: "的", pinyin: "de", meaning: "partícula possessiva", suggestions: [{"pinyin":"de","groupOrder":5,"order":0}] },
  "了": { hanzi: "了", pinyin: "le", meaning: "partícula de aspecto" },
  "不_2": { hanzi: "不", pinyin: "bù", meaning: "não" },
  "在_2": { hanzi: "在", pinyin: "zài", meaning: "estar em", suggestions: [{"pinyin":"zai","groupOrder":64,"order":0}] },
  "有_2": { hanzi: "有", pinyin: "yǒu", meaning: "ter", suggestions: [{"pinyin":"you","groupOrder":22,"order":0}] },
  "中_2": { hanzi: "中", pinyin: "zhōng", meaning: "meio, China" },
  "上_2": { hanzi: "上", pinyin: "shàng", meaning: "acima", suggestions: [{"pinyin":"shang","groupOrder":10,"order":0}] },
  "个_2": { hanzi: "个", pinyin: "gè", meaning: "classificador geral", suggestions: [{"pinyin":"ge","groupOrder":9,"order":0}] },
  "到": { hanzi: "到", pinyin: "dào", meaning: "chegar", suggestions: [{"pinyin":"dao","groupOrder":74,"order":1}] },
  "说_2": { hanzi: "说", pinyin: "shuō", meaning: "dizer" },
  "们_2": { hanzi: "们", pinyin: "men", meaning: "marcador de plural" },
  "为_2": { hanzi: "为", pinyin: "wèi", meaning: "para, por" },
  "子_2": { hanzi: "子", pinyin: "zǐ", meaning: "filho, semente" },
  "和_3": { hanzi: "和", pinyin: "hé", meaning: "e, com" },
  "地": { hanzi: "地", pinyin: "dì", meaning: "terra, chão" },
  "道": { hanzi: "道", pinyin: "dào", meaning: "caminho, via" },
  "时": { hanzi: "时", pinyin: "shí", meaning: "tempo", suggestions: [{"pinyin":"shi","groupOrder":3,"order":2}] },
  "年": { hanzi: "年", pinyin: "nián", meaning: "ano", suggestions: [{"pinyin":"nian","groupOrder":51,"order":0}] },
  "得": { hanzi: "得", pinyin: "de/dé/děi", meaning: "obter, poder" },
  "就": { hanzi: "就", pinyin: "jiù", meaning: "então, exatamente" },
  "下_2": { hanzi: "下", pinyin: "xià", meaning: "abaixo", suggestions: [{"pinyin":"xia","groupOrder":11,"order":0}] },
  "以_2": { hanzi: "以", pinyin: "yǐ", meaning: "com, usar" },
  "生": { hanzi: "生", pinyin: "shēng", meaning: "nascer, vida" },
  "会_2": { hanzi: "会", pinyin: "huì", meaning: "saber fazer, reunião" },
  "过": { hanzi: "过", pinyin: "guò", meaning: "passar", suggestions: [{"pinyin":"guo","groupOrder":71,"order":1}] },
  "做": { hanzi: "做", pinyin: "zuò", meaning: "fazer", suggestions: [{"pinyin":"zuo","groupOrder":21,"order":0}] },
  "想_2": { hanzi: "想", pinyin: "xiǎng", meaning: "pensar, querer" },
  "几_2": { hanzi: "几", pinyin: "jǐ/jī", meaning: "quantos, alguns" },
  "吗_2": { hanzi: "吗", pinyin: "ma", meaning: "partícula interrogativa", suggestions: [{"pinyin":"ma","groupOrder":49,"order":2}] },
  "呢_2": { hanzi: "呢", pinyin: "ne", meaning: "partícula interrogativa" },
  "吧_2": { hanzi: "吧", pinyin: "ba", meaning: "partícula sugestiva" },
  "啊": { hanzi: "啊", pinyin: "ā", meaning: "partícula exclamativa" },
  "叫_2": { hanzi: "叫", pinyin: "jiào", meaning: "chamar, ser chamado" },
  "爱": { hanzi: "爱", pinyin: "ài", meaning: "amor, amar" },
  "对_2": { hanzi: "对", pinyin: "duì", meaning: "correto, para" },
  "自": { hanzi: "自", pinyin: "zì", meaning: "próprio" },
  "事": { hanzi: "事", pinyin: "shì", meaning: "assunto, coisa" },
  "起": { hanzi: "起", pinyin: "qǐ", meaning: "levantar", suggestions: [{"pinyin":"qi","groupOrder":47,"order":1}] },
  "还_2": { hanzi: "还", pinyin: "hái/huán", meaning: "ainda, devolver" },
  "家_2": { hanzi: "家", pinyin: "jiā", meaning: "casa, família" },
  "方": { hanzi: "方", pinyin: "fāng", meaning: "quadrado, direção" },
  "开": { hanzi: "开", pinyin: "kāi", meaning: "abrir" },
  "手": { hanzi: "手", pinyin: "shǒu", meaning: "mão" },
  "从": { hanzi: "从", pinyin: "cóng", meaning: "de, desde" },
  "现": { hanzi: "现", pinyin: "xiàn", meaning: "aparecer, presente" },
  "己": { hanzi: "己", pinyin: "jǐ", meaning: "próprio" },
  "者": { hanzi: "者", pinyin: "zhě", meaning: "pessoa, -ista" },
  "把": { hanzi: "把", pinyin: "bǎ", meaning: "segurar, marcador de objeto" },
  "见": { hanzi: "见", pinyin: "jiàn", meaning: "ver" },
  "第": { hanzi: "第", pinyin: "dì", meaning: "prefixo ordinal" },
  "长": { hanzi: "长", pinyin: "cháng/zhǎng", meaning: "longo, crescer" },
  "最_2": { hanzi: "最", pinyin: "zuì", meaning: "mais (superlativo)" },
  "分": { hanzi: "分", pinyin: "fēn/fèn", meaning: "dividir, minuto" },
  "前": { hanzi: "前", pinyin: "qián", meaning: "frente, anterior" },
  "外": { hanzi: "外", pinyin: "wài", meaning: "fora" },
  "定": { hanzi: "定", pinyin: "dìng", meaning: "fixo, decidir" },
  "给_3": { hanzi: "给", pinyin: "gěi", meaning: "dar, para" },
  "成": { hanzi: "成", pinyin: "chéng", meaning: "tornar-se, sucesso" },
  "当": { hanzi: "当", pinyin: "dāng/dàng", meaning: "quando, servir como" },
  "体": { hanzi: "体", pinyin: "tǐ", meaning: "corpo" },
  "新": { hanzi: "新", pinyin: "xīn", meaning: "novo", suggestions: [{"pinyin":"xin","groupOrder":31,"order":0}] },
  "知": { hanzi: "知", pinyin: "zhī", meaning: "saber", suggestions: [{"pinyin":"zhi","groupOrder":73,"order":0}] },
  "等_2": { hanzi: "等", pinyin: "děng", meaning: "esperar, etc." },
  "老_2": { hanzi: "老", pinyin: "lǎo", meaning: "velho", suggestions: [{"pinyin":"lao","groupOrder":58,"order":0}] },
  "听": { hanzi: "听", pinyin: "tīng", meaning: "ouvir" },
  "读": { hanzi: "读", pinyin: "dú", meaning: "ler" },
  "话_2": { hanzi: "话", pinyin: "huà", meaning: "palavra, fala" },
  "住": { hanzi: "住", pinyin: "zhù", meaning: "morar, viver" },
  "路": { hanzi: "路", pinyin: "lù", meaning: "caminho, estrada" },
  "走": { hanzi: "走", pinyin: "zǒu", meaning: "andar, caminhar" },
  "跑": { hanzi: "跑", pinyin: "pǎo", meaning: "correr" },
  "站": { hanzi: "站", pinyin: "zhàn", meaning: "ficar de pé, estação" },
  "睡": { hanzi: "睡", pinyin: "shuì", meaning: "dormir" },
  "觉": { hanzi: "觉", pinyin: "jiào/jué", meaning: "dormir, sentir" },
  "穿": { hanzi: "穿", pinyin: "chuān", meaning: "vestir, usar roupa" },
  "衣": { hanzi: "衣", pinyin: "yī", meaning: "roupa", suggestions: [{"pinyin":"yi","groupOrder":41,"order":2}] },
  "服": { hanzi: "服", pinyin: "fú", meaning: "roupa, servir" },
  "鞋": { hanzi: "鞋", pinyin: "xié", meaning: "sapato" },
  "帽": { hanzi: "帽", pinyin: "mào", meaning: "chapéu" },
  "眼": { hanzi: "眼", pinyin: "yǎn", meaning: "olho" },
  "睛": { hanzi: "睛", pinyin: "jīng", meaning: "olho (parte de 眼睛)" },
  "耳": { hanzi: "耳", pinyin: "ěr", meaning: "orelha", suggestions: [{"pinyin":"er","groupOrder":42,"order":1}] },
  "朵": { hanzi: "朵", pinyin: "duǒ", meaning: "classificador para flores e orelhas" },
  "口_3": { hanzi: "口", pinyin: "kǒu", meaning: "boca" },
  "鼻": { hanzi: "鼻", pinyin: "bí", meaning: "nariz" },
  "头": { hanzi: "头", pinyin: "tóu", meaning: "cabeça" },
  "脸": { hanzi: "脸", pinyin: "liǎn", meaning: "rosto" },
  "脚": { hanzi: "脚", pinyin: "jiǎo", meaning: "pé" },
  "腿": { hanzi: "腿", pinyin: "tuǐ", meaning: "perna" },
  "才": { hanzi: "才", pinyin: "cái", meaning: "apenas, talento" },
  "民": { hanzi: "民", pinyin: "mín", meaning: "povo" },
  "文_2": { hanzi: "文", pinyin: "wén", meaning: "texto, cultura" },
  "理": { hanzi: "理", pinyin: "lǐ", meaning: "razão, gerenciar" },
  "发_2": { hanzi: "发", pinyin: "fā", meaning: "emitir, desenvolver" },
  "气": { hanzi: "气", pinyin: "qì", meaning: "ar, energia" },
  "动": { hanzi: "动", pinyin: "dòng", meaning: "mover" },
  "意": { hanzi: "意", pinyin: "yì", meaning: "significado, intenção" },
  "心": { hanzi: "心", pinyin: "xīn", meaning: "coração", suggestions: [{"pinyin":"xin","groupOrder":31,"order":1}] },
  "面": { hanzi: "面", pinyin: "miàn", meaning: "face, superfície" },
  "力": { hanzi: "力", pinyin: "lì", meaning: "força" },
  "本_2": { hanzi: "本", pinyin: "běn", meaning: "origem, livro" },
  "经": { hanzi: "经", pinyin: "jīng", meaning: "passar por, sutra" },
  "工_2": { hanzi: "工", pinyin: "gōng", meaning: "trabalho, operário" },
  "然": { hanzi: "然", pinyin: "rán", meaning: "assim, naturalmente" },
  "没": { hanzi: "没", pinyin: "méi", meaning: "não ter", suggestions: [{"pinyin":"mei","groupOrder":23,"order":0}] },
  "间": { hanzi: "间", pinyin: "jiān/jiàn", meaning: "entre, espaço" },
  "行_2": { hanzi: "行", pinyin: "xíng/háng", meaning: "andar, linha" },
  "相": { hanzi: "相", pinyin: "xiāng/xiàng", meaning: "mutuamente, aparência" },
  "因": { hanzi: "因", pinyin: "yīn", meaning: "causa" },
  "同": { hanzi: "同", pinyin: "tóng", meaning: "mesmo" },
  "已": { hanzi: "已", pinyin: "yǐ", meaning: "já" },
  "些": { hanzi: "些", pinyin: "xiē", meaning: "alguns" },
  "无": { hanzi: "无", pinyin: "wú", meaning: "não ter, sem" },
  "认_2": { hanzi: "认", pinyin: "rèn", meaning: "reconhecer", suggestions: [{"pinyin":"ren","groupOrder":4,"order":1}] },
  "识_2": { hanzi: "识", pinyin: "shí/shì", meaning: "conhecimento, reconhecer" },
  "觉_2": { hanzi: "觉", pinyin: "jiào/jué", meaning: "sentir, perceber" },
  "记": { hanzi: "记", pinyin: "jì", meaning: "anotar, lembrar" },
  "忘": { hanzi: "忘", pinyin: "wàng", meaning: "esquecer" },
  "懂": { hanzi: "懂", pinyin: "dǒng", meaning: "entender" },
  "比": { hanzi: "比", pinyin: "bǐ", meaning: "comparar" },
  "较": { hanzi: "较", pinyin: "jiào", meaning: "comparativamente" },
  "更": { hanzi: "更", pinyin: "gèng", meaning: "mais ainda" },
  "特": { hanzi: "特", pinyin: "tè", meaning: "especial" },
  "别": { hanzi: "别", pinyin: "bié", meaning: "não (imperativo), especial" },
  "其": { hanzi: "其", pinyin: "qí", meaning: "seu, tal" },
  "实": { hanzi: "实", pinyin: "shí", meaning: "real, verdadeiro" },
  "真_2": { hanzi: "真", pinyin: "zhēn", meaning: "verdadeiro, realmente" },
  "假": { hanzi: "假", pinyin: "jiǎ/jià", meaning: "falso, férias" },
  "错": { hanzi: "错", pinyin: "cuò", meaning: "errado" },
  "完": { hanzi: "完", pinyin: "wán", meaning: "terminar, completo" },
  "始": { hanzi: "始", pinyin: "shǐ", meaning: "começar" },
  "终": { hanzi: "终", pinyin: "zhōng", meaning: "fim" },
  "结": { hanzi: "结", pinyin: "jié/jiē", meaning: "nó, resultado" },
  "束": { hanzi: "束", pinyin: "shù", meaning: "feixe, restringir" },
  "决": { hanzi: "决", pinyin: "jué", meaning: "decidir" },
  "选": { hanzi: "选", pinyin: "xuǎn", meaning: "escolher" },
  "择": { hanzi: "择", pinyin: "zé", meaning: "escolher, selecionar" },
  "改": { hanzi: "改", pinyin: "gǎi", meaning: "mudar, modificar" },
  "变": { hanzi: "变", pinyin: "biàn", meaning: "mudar, transformar" },
  "化": { hanzi: "化", pinyin: "huà", meaning: "transformar, -izar" },
  "需": { hanzi: "需", pinyin: "xū", meaning: "precisar" },
  "必": { hanzi: "必", pinyin: "bì", meaning: "certamente, deve" },
  "须": { hanzi: "须", pinyin: "xū", meaning: "dever, bigode" },
  "该": { hanzi: "该", pinyin: "gāi", meaning: "dever" },
  "应": { hanzi: "应", pinyin: "yīng/yìng", meaning: "dever, responder" },
  "而": { hanzi: "而", pinyin: "ér", meaning: "mas, e (conectivo)" },
  "且": { hanzi: "且", pinyin: "qiě", meaning: "além disso" },
  "况": { hanzi: "况", pinyin: "kuàng", meaning: "situação, além disso" },
  "若": { hanzi: "若", pinyin: "ruò", meaning: "se, como" },
  "虽": { hanzi: "虽", pinyin: "suī", meaning: "embora" },
  "尽": { hanzi: "尽", pinyin: "jǐn/jìn", meaning: "esgotar, embora" },
  "管": { hanzi: "管", pinyin: "guǎn", meaning: "tubo, gerenciar, embora" },
  "除": { hanzi: "除", pinyin: "chú", meaning: "remover, exceto" },
  "非": { hanzi: "非", pinyin: "fēi", meaning: "não ser, errado" },
  "否": { hanzi: "否", pinyin: "fǒu", meaning: "não (forma negativa)" },
  "另": { hanzi: "另", pinyin: "lìng", meaning: "outro" },
  "各": { hanzi: "各", pinyin: "gè", meaning: "cada" },
  "每": { hanzi: "每", pinyin: "měi", meaning: "cada, todo" },
  "任": { hanzi: "任", pinyin: "rèn", meaning: "qualquer, cargo" },
  "何": { hanzi: "何", pinyin: "hé", meaning: "qual, qualquer" },
  "某": { hanzi: "某", pinyin: "mǒu", meaning: "certo, algum" },
  "整": { hanzi: "整", pinyin: "zhěng", meaning: "inteiro, arrumar" },
  "般": { hanzi: "般", pinyin: "bān", meaning: "tipo, maneira" },
  "普": { hanzi: "普", pinyin: "pǔ", meaning: "universal, comum" },
  "遍": { hanzi: "遍", pinyin: "biàn", meaning: "vez, por toda parte" },
  "共": { hanzi: "共", pinyin: "gòng", meaning: "junto, total" },
  "总": { hanzi: "总", pinyin: "zǒng", meaning: "total, sempre" },
  "互": { hanzi: "互", pinyin: "hù", meaning: "mútuo" },
  "彼": { hanzi: "彼", pinyin: "bǐ", meaning: "aquele" },
  "此": { hanzi: "此", pinyin: "cǐ", meaning: "este" },
  "双": { hanzi: "双", pinyin: "shuāng", meaning: "par, duplo" },
  "单": { hanzi: "单", pinyin: "dān", meaning: "único, simples" },
  "独": { hanzi: "独", pinyin: "dú", meaning: "sozinho" },
  "孤": { hanzi: "孤", pinyin: "gū", meaning: "solitário, órfão" },
  "众": { hanzi: "众", pinyin: "zhòng", meaning: "multidão" },
  "群": { hanzi: "群", pinyin: "qún", meaning: "grupo" },
  "集": { hanzi: "集", pinyin: "jí", meaning: "reunir, coleção" },
  "合": { hanzi: "合", pinyin: "hé", meaning: "combinar, adequado" },
  "联": { hanzi: "联", pinyin: "lián", meaning: "conectar, unir" },
  "接": { hanzi: "接", pinyin: "jiē", meaning: "conectar, receber" },
  "系_2": { hanzi: "系", pinyin: "xì/jì", meaning: "sistema, amarrar" },
  "关": { hanzi: "关", pinyin: "guān", meaning: "fechar, relação" },
  "键": { hanzi: "键", pinyin: "jiàn", meaning: "chave, tecla" },
  "钥": { hanzi: "钥", pinyin: "yào", meaning: "chave (parte de 钥匙)" },
  "匙": { hanzi: "匙", pinyin: "shi", meaning: "colher, chave" },
  "锁": { hanzi: "锁", pinyin: "suǒ", meaning: "tranca, trancar" },
  "闭": { hanzi: "闭", pinyin: "bì", meaning: "fechar" },
  "启": { hanzi: "启", pinyin: "qǐ", meaning: "abrir, iniciar" },
  "推": { hanzi: "推", pinyin: "tuī", meaning: "empurrar" },
  "拉": { hanzi: "拉", pinyin: "lā", meaning: "puxar" },
  "抬": { hanzi: "抬", pinyin: "tái", meaning: "levantar" },
  "举": { hanzi: "举", pinyin: "jǔ", meaning: "levantar, realizar" },
  "放": { hanzi: "放", pinyin: "fàng", meaning: "colocar, soltar" },
  "置": { hanzi: "置", pinyin: "zhì", meaning: "colocar, posição" },
  "摆": { hanzi: "摆", pinyin: "bǎi", meaning: "arranjar, balançar" },
  "排": { hanzi: "排", pinyin: "pái", meaning: "arranjar, fila" },
  "列": { hanzi: "列", pinyin: "liè", meaning: "lista, alinhar" },
  "序": { hanzi: "序", pinyin: "xù", meaning: "ordem, sequência" },
  "次": { hanzi: "次", pinyin: "cì", meaning: "vez, próximo" },
  "级": { hanzi: "级", pinyin: "jí", meaning: "nível, classe" },
  "层": { hanzi: "层", pinyin: "céng", meaning: "camada, andar" },
  "段": { hanzi: "段", pinyin: "duàn", meaning: "seção, parágrafo" },
  "落": { hanzi: "落", pinyin: "luò/là/lào", meaning: "cair, deixar cair" },
  "版": { hanzi: "版", pinyin: "bǎn", meaning: "edição, placa" },
  "报": { hanzi: "报", pinyin: "bào", meaning: "jornal, reportar" },
  "杂": { hanzi: "杂", pinyin: "zá", meaning: "misturado, variado" },
  "志": { hanzi: "志", pinyin: "zhì", meaning: "revista, vontade" },
  "刊": { hanzi: "刊", pinyin: "kān", meaning: "publicação", suggestions: [{"pinyin":"kan","groupOrder":17,"order":1}] },
  "登": { hanzi: "登", pinyin: "dēng", meaning: "publicar, subir" },
  "载": { hanzi: "载", pinyin: "zǎi/zài", meaning: "carregar, registrar" },
  "印": { hanzi: "印", pinyin: "yìn", meaning: "imprimir, selo" },
  "刷": { hanzi: "刷", pinyin: "shuā/shuà", meaning: "escovar, imprimir" },
  "编": { hanzi: "编", pinyin: "biān", meaning: "editar, compilar" },
  "译": { hanzi: "译", pinyin: "yì", meaning: "traduzir" },
  "著": { hanzi: "著", pinyin: "zhù/zhe/zhuó", meaning: "escrever, obra" },
  "述": { hanzi: "述", pinyin: "shù", meaning: "declarar, narrativa" },
  "论": { hanzi: "论", pinyin: "lùn", meaning: "teoria, discutir" },
  "议": { hanzi: "议", pinyin: "yì", meaning: "discussão, proposta" },
  "评": { hanzi: "评", pinyin: "píng", meaning: "criticar, avaliar" },
  "价": { hanzi: "价", pinyin: "jià", meaning: "preço, valor" },
  "值": { hanzi: "值", pinyin: "zhí", meaning: "valor" },
  "费": { hanzi: "费", pinyin: "fèi", meaning: "taxa, gastar" },
  "花": { hanzi: "花", pinyin: "huā", meaning: "flor, gastar" },
  "币": { hanzi: "币", pinyin: "bì", meaning: "moeda" },
  "元": { hanzi: "元", pinyin: "yuán", meaning: "yuan, origem" },
  "块_2": { hanzi: "块", pinyin: "kuài", meaning: "pedaço, yuan (coloquial)" },
  "角": { hanzi: "角", pinyin: "jiǎo/jué", meaning: "chifre, 10 centavos" },
  "毛": { hanzi: "毛", pinyin: "máo", meaning: "pelo, 10 centavos" },
  "富": { hanzi: "富", pinyin: "fù", meaning: "rico" },
  "贫": { hanzi: "贫", pinyin: "pín", meaning: "pobre" },
  "穷": { hanzi: "穷", pinyin: "qióng", meaning: "pobre" },
  "贵_3": { hanzi: "贵", pinyin: "guì", meaning: "caro, nobre" },
  "廉": { hanzi: "廉", pinyin: "lián", meaning: "barato, honesto" },
  "宜": { hanzi: "宜", pinyin: "yí", meaning: "apropriado, barato" },
  "赚": { hanzi: "赚", pinyin: "zhuàn", meaning: "ganhar dinheiro" },
  "挣": { hanzi: "挣", pinyin: "zhèng/zhēng", meaning: "ganhar, lutar" },
  "赔": { hanzi: "赔", pinyin: "péi", meaning: "compensar perda" },
  "亏": { hanzi: "亏", pinyin: "kuī", meaning: "perder, déficit" },
  "损": { hanzi: "损", pinyin: "sǔn", meaning: "perder, danificar" },
  "失": { hanzi: "失", pinyin: "shī", meaning: "perder" },
  "丢": { hanzi: "丢", pinyin: "diū", meaning: "perder, jogar fora" },
  "遗": { hanzi: "遗", pinyin: "yí", meaning: "deixar, legado" },
  "留": { hanzi: "留", pinyin: "liú", meaning: "permanecer, deixar" },
  "存": { hanzi: "存", pinyin: "cún", meaning: "existir, guardar" },
  "保": { hanzi: "保", pinyin: "bǎo", meaning: "proteger, manter" },
  "护": { hanzi: "护", pinyin: "hù", meaning: "proteger" },
  "守": { hanzi: "守", pinyin: "shǒu", meaning: "guardar, defender" },
  "卫": { hanzi: "卫", pinyin: "wèi", meaning: "defender, guarda" },
  "防": { hanzi: "防", pinyin: "fáng", meaning: "prevenir, defender" },
  "备": { hanzi: "备", pinyin: "bèi", meaning: "preparar" },
  "预": { hanzi: "预", pinyin: "yù", meaning: "prévio, antecipado" },
  "测": { hanzi: "测", pinyin: "cè", meaning: "medir, prever" },
  "算": { hanzi: "算", pinyin: "suàn", meaning: "calcular, considerar" },
  "数": { hanzi: "数", pinyin: "shù/shǔ", meaning: "número, contar" },
  "计": { hanzi: "计", pinyin: "jì", meaning: "calcular, plano" },
  "划": { hanzi: "划", pinyin: "huà/huá", meaning: "plano, remar" },
  "案": { hanzi: "案", pinyin: "àn", meaning: "caso, plano" },
  "略": { hanzi: "略", pinyin: "lüè", meaning: "estratégia, resumo" },
  "策": { hanzi: "策", pinyin: "cè", meaning: "estratégia, açoitar" },
  "谋": { hanzi: "谋", pinyin: "móu", meaning: "planejar, conspirar" },
  "虑": { hanzi: "虑", pinyin: "lǜ", meaning: "considerar, preocupar" },
  "哲": { hanzi: "哲", pinyin: "zhé", meaning: "filosofia, sábio" },
  "慧": { hanzi: "慧", pinyin: "huì", meaning: "sabedoria" },
  "智": { hanzi: "智", pinyin: "zhì", meaning: "sabedoria, inteligência" },
  "愚": { hanzi: "愚", pinyin: "yú", meaning: "tolo" },
  "蠢": { hanzi: "蠢", pinyin: "chǔn", meaning: "estúpido" },
  "聪": { hanzi: "聪", pinyin: "cōng", meaning: "inteligente, agudo" },
  "敏": { hanzi: "敏", pinyin: "mǐn", meaning: "ágil, sensível" },
  "钝": { hanzi: "钝", pinyin: "dùn", meaning: "embotado, lento" },
  "伶": { hanzi: "伶", pinyin: "líng", meaning: "esperto" },
  "俐": { hanzi: "俐", pinyin: "lì", meaning: "esperto, hábil" },
  "巧": { hanzi: "巧", pinyin: "qiǎo", meaning: "habilidoso, coincidência" },
  "拙": { hanzi: "拙", pinyin: "zhuō", meaning: "desajeitado" },
  "笨": { hanzi: "笨", pinyin: "bèn", meaning: "estúpido, pesado" },
  "呆": { hanzi: "呆", pinyin: "dāi", meaning: "tolo, ficar" },
  "傻": { hanzi: "傻", pinyin: "shǎ", meaning: "tolo, bobo" },
  "疯": { hanzi: "疯", pinyin: "fēng", meaning: "louco" },
  "狂": { hanzi: "狂", pinyin: "kuáng", meaning: "louco, fanático" },
  "癫": { hanzi: "癫", pinyin: "diān", meaning: "insano, epilepsia" },
  "痴": { hanzi: "痴", pinyin: "chī", meaning: "idiota, obcecado" },
  "迷": { hanzi: "迷", pinyin: "mí", meaning: "confuso, fã" },
  "惑": { hanzi: "惑", pinyin: "huò", meaning: "confuso, dúvida" },
  "糊": { hanzi: "糊", pinyin: "hú/hù", meaning: "confuso, pasta" },
  "涂": { hanzi: "涂", pinyin: "tú", meaning: "aplicar, sujar" },
  "抹": { hanzi: "抹", pinyin: "mǒ/mā/mò", meaning: "esfregar, apagar" },
  "擦": { hanzi: "擦", pinyin: "cā", meaning: "limpar, esfregar" },
  "刮": { hanzi: "刮", pinyin: "guā", meaning: "raspar, ventar" },
  "削": { hanzi: "削", pinyin: "xuē/xiāo", meaning: "cortar, reduzir" },
  "割": { hanzi: "割", pinyin: "gē", meaning: "cortar, colher" },
  "砍": { hanzi: "砍", pinyin: "kǎn", meaning: "cortar, picar" },
  "劈": { hanzi: "劈", pinyin: "pī/pǐ", meaning: "rachar, dividir" },
  "裂": { hanzi: "裂", pinyin: "liè", meaning: "rachadura, dividir" },
  "碎": { hanzi: "碎", pinyin: "suì", meaning: "quebrado, fragmentos" },
  "破": { hanzi: "破", pinyin: "pò", meaning: "quebrado, romper" },
  "损_2": { hanzi: "损", pinyin: "sǔn", meaning: "danificar" },
  "坏": { hanzi: "坏", pinyin: "huài", meaning: "ruim, estragado" },
  "烂": { hanzi: "烂", pinyin: "làn", meaning: "podre, em excesso" },
  "腐": { hanzi: "腐", pinyin: "fǔ", meaning: "podre, corrupto" },
  "朽": { hanzi: "朽", pinyin: "xiǔ", meaning: "podre, decadente" },
  "蚀": { hanzi: "蚀", pinyin: "shí", meaning: "corroer" },
  "锈": { hanzi: "锈", pinyin: "xiù", meaning: "ferrugem" },
  "霉": { hanzi: "霉", pinyin: "méi", meaning: "mofo" },
  "臭": { hanzi: "臭", pinyin: "chòu/xiù", meaning: "fedorento" },
  "香": { hanzi: "香", pinyin: "xiāng", meaning: "fragrante" },
  "芳": { hanzi: "芳", pinyin: "fāng", meaning: "fragrante" },
  "馨": { hanzi: "馨", pinyin: "xīn", meaning: "fragrante" },
  "芬": { hanzi: "芬", pinyin: "fēn", meaning: "fragrância" },
  "馥": { hanzi: "馥", pinyin: "fù", meaning: "fragrância rica" },
  "郁": { hanzi: "郁", pinyin: "yù", meaning: "luxuriante, deprimido" },
  "闷": { hanzi: "闷", pinyin: "mēn/mèn", meaning: "abafado, deprimido" },
  "沉": { hanzi: "沉", pinyin: "chén", meaning: "afundar, pesado" },
  "浮": { hanzi: "浮", pinyin: "fú", meaning: "flutuar" },
  "漂_2": { hanzi: "漂", pinyin: "piāo/piǎo/piào", meaning: "flutuar, bonito" },
  "泛": { hanzi: "泛", pinyin: "fàn", meaning: "flutuar, geral" },
  "溢": { hanzi: "溢", pinyin: "yì", meaning: "transbordar" },
  "洒": { hanzi: "洒", pinyin: "sǎ", meaning: "respingar, derramar" },
  "泼": { hanzi: "泼", pinyin: "pō", meaning: "respingar, vigoroso" },
  "喷": { hanzi: "喷", pinyin: "pēn/pèn", meaning: "pulverizar" },
  "洒_2": { hanzi: "洒", pinyin: "sǎ", meaning: "aspergir" },
  "淋": { hanzi: "淋", pinyin: "lín/lìn", meaning: "derramar, regar" },
  "百_2": { hanzi: "百", pinyin: "bǎi", meaning: "cem", suggestions: [{"pinyin":"bai","groupOrder":36,"order":1}] },
  "零_2": { hanzi: "零", pinyin: "líng", meaning: "zero" },
  "两_2": { hanzi: "两", pinyin: "liǎng", meaning: "dois (antes de medidas)" },
  "半": { hanzi: "半", pinyin: "bàn", meaning: "metade" },
  "双_2": { hanzi: "双", pinyin: "shuāng", meaning: "par" },
  "黄": { hanzi: "黄", pinyin: "huáng", meaning: "amarelo", suggestions: [{"pinyin":"huang","groupOrder":40,"order":0}] },
  "蓝": { hanzi: "蓝", pinyin: "lán", meaning: "azul", suggestions: [{"pinyin":"lan","groupOrder":38,"order":0}] },
  "绿": { hanzi: "绿", pinyin: "lǜ", meaning: "verde", suggestions: [{"pinyin":"lv","groupOrder":39,"order":0}] },
  "黑": { hanzi: "黑", pinyin: "hēi", meaning: "preto", suggestions: [{"pinyin":"hei","groupOrder":35,"order":0}] },
  "灰": { hanzi: "灰", pinyin: "huī", meaning: "cinza" },
  "紫": { hanzi: "紫", pinyin: "zǐ", meaning: "roxo" },
  "橙": { hanzi: "橙", pinyin: "chéng", meaning: "laranja" },
  "粉": { hanzi: "粉", pinyin: "fěn", meaning: "rosa" },
  "棕": { hanzi: "棕", pinyin: "zōng", meaning: "marrom" },
  "褐": { hanzi: "褐", pinyin: "hè", meaning: "marrom escuro" },
  "金": { hanzi: "金", pinyin: "jīn", meaning: "dourado, ouro" },
  "银": { hanzi: "银", pinyin: "yín", meaning: "prata, prateado" },
  "青": { hanzi: "青", pinyin: "qīng", meaning: "azul-esverdeado" },
  "爸": { hanzi: "爸", pinyin: "bà", meaning: "pai", suggestions: [{"pinyin":"ba","groupOrder":48,"order":2}] },
  "妈_2": { hanzi: "妈", pinyin: "mā", meaning: "mãe", suggestions: [{"pinyin":"ma","groupOrder":49,"order":0}] },
  "哥": { hanzi: "哥", pinyin: "gē", meaning: "irmão mais velho", suggestions: [{"pinyin":"ge","groupOrder":9,"order":1}] },
  "姐": { hanzi: "姐", pinyin: "jiě", meaning: "irmã mais velha" },
  "弟": { hanzi: "弟", pinyin: "dì", meaning: "irmão mais novo" },
  "妹": { hanzi: "妹", pinyin: "mèi", meaning: "irmã mais nova" },
  "儿_2": { hanzi: "儿", pinyin: "ér", meaning: "filho", suggestions: [{"pinyin":"er","groupOrder":42,"order":2}] },
  "女_2": { hanzi: "女", pinyin: "nǚ", meaning: "filha, mulher" },
  "孩": { hanzi: "孩", pinyin: "hái", meaning: "criança" },
  "祖": { hanzi: "祖", pinyin: "zǔ", meaning: "avô, ancestral" },
  "爷": { hanzi: "爷", pinyin: "yé", meaning: "avô paterno" },
  "奶": { hanzi: "奶", pinyin: "nǎi", meaning: "avó, leite" },
  "公": { hanzi: "公", pinyin: "gōng", meaning: "público, sogro" },
  "婆": { hanzi: "婆", pinyin: "pó", meaning: "sogra, velha senhora" },
  "夫": { hanzi: "夫", pinyin: "fū", meaning: "marido" },
  "妻": { hanzi: "妻", pinyin: "qī", meaning: "esposa" },
  "叔": { hanzi: "叔", pinyin: "shū", meaning: "tio paterno mais novo" },
  "伯": { hanzi: "伯", pinyin: "bó", meaning: "tio paterno mais velho" },
  "姨": { hanzi: "姨", pinyin: "yí", meaning: "tia materna" },
  "姑": { hanzi: "姑", pinyin: "gū", meaning: "tia paterna" },
  "舅": { hanzi: "舅", pinyin: "jiù", meaning: "tio materno" },
  "侄": { hanzi: "侄", pinyin: "zhí", meaning: "sobrinho" },
  "甥": { hanzi: "甥", pinyin: "shēng", meaning: "sobrinho de irmã" },
  "孙": { hanzi: "孙", pinyin: "sūn", meaning: "neto" },
  "饭": { hanzi: "饭", pinyin: "fàn", meaning: "arroz, comida" },
  "菜_2": { hanzi: "菜", pinyin: "cài", meaning: "vegetal, prato" },
  "鸡": { hanzi: "鸡", pinyin: "jī", meaning: "frango" },
  "蛋": { hanzi: "蛋", pinyin: "dàn", meaning: "ovo" },
  "咖": { hanzi: "咖", pinyin: "kā", meaning: "café" },
  "啡": { hanzi: "啡", pinyin: "fēi", meaning: "café" },
  "奶_2": { hanzi: "奶", pinyin: "nǎi", meaning: "leite" },
  "果": { hanzi: "果", pinyin: "guǒ", meaning: "fruta" },
  "汤_2": { hanzi: "汤", pinyin: "tāng", meaning: "sopa" },
  "面_2": { hanzi: "面", pinyin: "miàn", meaning: "macarrão" },
  "包": { hanzi: "包", pinyin: "bāo", meaning: "pão, embrulhar" },
  "酒": { hanzi: "酒", pinyin: "jiǔ", meaning: "álcool" },
  "盐": { hanzi: "盐", pinyin: "yán", meaning: "sal" },
  "油": { hanzi: "油", pinyin: "yóu", meaning: "óleo" },
  "酱": { hanzi: "酱", pinyin: "jiàng", meaning: "molho" },
  "豆": { hanzi: "豆", pinyin: "dòu", meaning: "feijão" },
  "腐_2": { hanzi: "腐", pinyin: "fǔ", meaning: "tofu, podre" },
  "米": { hanzi: "米", pinyin: "mǐ", meaning: "arroz (grão)" },
  "粉_2": { hanzi: "粉", pinyin: "fěn", meaning: "pó, macarrão de arroz" },
  "饺": { hanzi: "饺", pinyin: "jiǎo", meaning: "bolinho" },
  "馒": { hanzi: "馒", pinyin: "mán", meaning: "pãozinho cozido no vapor" },
  "头_2": { hanzi: "头", pinyin: "tou", meaning: "cabeça (parte de 馒头)" },
  "饼": { hanzi: "饼", pinyin: "bǐng", meaning: "bolo achatado" },
  "糕": { hanzi: "糕", pinyin: "gāo", meaning: "bolo" },
  "粥": { hanzi: "粥", pinyin: "zhōu", meaning: "mingau" },
  "虾": { hanzi: "虾", pinyin: "xiā", meaning: "camarão" },
  "蟹": { hanzi: "蟹", pinyin: "xiè", meaning: "caranguejo" },
  "贝": { hanzi: "贝", pinyin: "bèi", meaning: "marisco, concha" },
  "鸭": { hanzi: "鸭", pinyin: "yā", meaning: "pato" },
  "鹅": { hanzi: "鹅", pinyin: "é", meaning: "ganso" },
  "猫": { hanzi: "猫", pinyin: "māo", meaning: "gato" },
  "狗": { hanzi: "狗", pinyin: "gǒu", meaning: "cachorro" },
  "鸟": { hanzi: "鸟", pinyin: "niǎo", meaning: "pássaro" },
  "牛_2": { hanzi: "牛", pinyin: "niú", meaning: "vaca" },
  "羊": { hanzi: "羊", pinyin: "yáng", meaning: "ovelha" },
  "猪": { hanzi: "猪", pinyin: "zhū", meaning: "porco" },
  "虎": { hanzi: "虎", pinyin: "hǔ", meaning: "tigre" },
  "蛇": { hanzi: "蛇", pinyin: "shé", meaning: "cobra" },
  "兔": { hanzi: "兔", pinyin: "tù", meaning: "coelho" },
  "鼠": { hanzi: "鼠", pinyin: "shǔ", meaning: "rato" },
  "狼": { hanzi: "狼", pinyin: "láng", meaning: "lobo" },
  "熊": { hanzi: "熊", pinyin: "xióng", meaning: "urso" },
  "豹": { hanzi: "豹", pinyin: "bào", meaning: "leopardo" },
  "狮": { hanzi: "狮", pinyin: "shī", meaning: "leão" },
  "象": { hanzi: "象", pinyin: "xiàng", meaning: "elefante" },
  "猴": { hanzi: "猴", pinyin: "hóu", meaning: "macaco" },
  "鹿": { hanzi: "鹿", pinyin: "lù", meaning: "veado" },
  "鹰": { hanzi: "鹰", pinyin: "yīng", meaning: "águia" },
  "鸽": { hanzi: "鸽", pinyin: "gē", meaning: "pombo" },
  "鸡_2": { hanzi: "鸡", pinyin: "jī", meaning: "galinha" },
  "蚁": { hanzi: "蚁", pinyin: "yǐ", meaning: "formiga" },
  "蜂": { hanzi: "蜂", pinyin: "fēng", meaning: "abelha" },
  "蝶": { hanzi: "蝶", pinyin: "dié", meaning: "borboleta" },
  "蝴": { hanzi: "蝴", pinyin: "hú", meaning: "borboleta (parte de 蝴蝶)" },
  "蜘": { hanzi: "蜘", pinyin: "zhī", meaning: "aranha (parte de 蜘蛛)" },
  "蛛": { hanzi: "蛛", pinyin: "zhū", meaning: "aranha" },
  "跳": { hanzi: "跳", pinyin: "tiào", meaning: "pular" },
  "飞": { hanzi: "飞", pinyin: "fēi", meaning: "voar" },
  "游": { hanzi: "游", pinyin: "yóu", meaning: "nadar, viajar" },
  "爬": { hanzi: "爬", pinyin: "pá", meaning: "escalar, rastejar" },
  "扔": { hanzi: "扔", pinyin: "rēng", meaning: "jogar fora" },
  "丢_2": { hanzi: "丢", pinyin: "diū", meaning: "perder, jogar" },
  "捡": { hanzi: "捡", pinyin: "jiǎn", meaning: "pegar, coletar" },
  "抓": { hanzi: "抓", pinyin: "zhuā", meaning: "agarrar" },
  "握": { hanzi: "握", pinyin: "wò", meaning: "segurar, apertar" },
  "抱": { hanzi: "抱", pinyin: "bào", meaning: "abraçar" },
  "摸": { hanzi: "摸", pinyin: "mō", meaning: "tocar, sentir" },
  "碰": { hanzi: "碰", pinyin: "pèng", meaning: "tocar, bater" },
  "���": { hanzi: "���", pinyin: "zhuàng", meaning: "colidir" },
  "打_2": { hanzi: "打", pinyin: "dǎ", meaning: "bater, jogar" },
  "踢": { hanzi: "踢", pinyin: "tī", meaning: "chutar" },
  "投": { hanzi: "投", pinyin: "tóu", meaning: "lançar, investir" },
  "掷": { hanzi: "掷", pinyin: "zhì", meaning: "arremessar" },
  "喊": { hanzi: "喊", pinyin: "hǎn", meaning: "gritar" },
  "叫_3": { hanzi: "叫", pinyin: "jiào", meaning: "chamar, gritar" },
  "哭": { hanzi: "哭", pinyin: "kū", meaning: "chorar" },
  "笑": { hanzi: "笑", pinyin: "xiào", meaning: "rir", suggestions: [{"pinyin":"xiao","groupOrder":30,"order":1}] },
  "唱": { hanzi: "唱", pinyin: "chàng", meaning: "cantar", suggestions: [{"pinyin":"chang","groupOrder":34,"order":2}] },
  "跳_2": { hanzi: "跳", pinyin: "tiào", meaning: "dançar, pular" },
  "舞": { hanzi: "舞", pinyin: "wǔ", meaning: "dançar" },
  "演": { hanzi: "演", pinyin: "yǎn", meaning: "atuar,演出" },
  "奏": { hanzi: "奏", pinyin: "zòu", meaning: "tocar música" },
  "弹": { hanzi: "弹", pinyin: "tán/dàn", meaning: "tocar (instrumento), bala" },
  "拉_2": { hanzi: "拉", pinyin: "lā", meaning: "tocar (violino)" },
  "吹": { hanzi: "吹", pinyin: "chuī", meaning: "soprar, tocar (flauta)" },
  "敲": { hanzi: "敲", pinyin: "qiāo", meaning: "bater, tocar (tambor)" },
  "长_2": { hanzi: "长", pinyin: "cháng", meaning: "longo", suggestions: [{"pinyin":"chang","groupOrder":34,"order":0}] },
  "短": { hanzi: "短", pinyin: "duǎn", meaning: "curto" },
  "低": { hanzi: "低", pinyin: "dī", meaning: "baixo" },
  "厚": { hanzi: "厚", pinyin: "hòu", meaning: "grosso" },
  "薄": { hanzi: "薄", pinyin: "báo/bó", meaning: "fino" },
  "宽": { hanzi: "宽", pinyin: "kuān", meaning: "largo" },
  "窄": { hanzi: "窄", pinyin: "zhǎi", meaning: "estreito" },
  "深": { hanzi: "深", pinyin: "shēn", meaning: "profundo" },
  "浅": { hanzi: "浅", pinyin: "qiǎn", meaning: "raso" },
  "重": { hanzi: "重", pinyin: "zhòng", meaning: "pesado" },
  "轻": { hanzi: "轻", pinyin: "qīng", meaning: "leve" },
  "快": { hanzi: "快", pinyin: "kuài", meaning: "rápido" },
  "慢": { hanzi: "慢", pinyin: "màn", meaning: "lento" },
  "早": { hanzi: "早", pinyin: "zǎo", meaning: "cedo" },
  "晚": { hanzi: "晚", pinyin: "wǎn", meaning: "tarde" },
  "热": { hanzi: "热", pinyin: "rè", meaning: "quente" },
  "冷": { hanzi: "冷", pinyin: "lěng", meaning: "frio" },
  "暖": { hanzi: "暖", pinyin: "nuǎn", meaning: "morno" },
  "凉": { hanzi: "凉", pinyin: "liáng/liàng", meaning: "fresco" },
  "干_2": { hanzi: "干", pinyin: "gān/gàn", meaning: "seco, fazer" },
  "湿": { hanzi: "湿", pinyin: "shī", meaning: "úmido" },
  "亮_2": { hanzi: "亮", pinyin: "liàng", meaning: "brilhante" },
  "暗": { hanzi: "暗", pinyin: "àn", meaning: "escuro" },
  "明_2": { hanzi: "明", pinyin: "míng", meaning: "brilhante, claro" },
  "亮_3": { hanzi: "亮", pinyin: "liàng", meaning: "luminoso" },
  "净": { hanzi: "净", pinyin: "jìng", meaning: "limpo" },
  "脏": { hanzi: "脏", pinyin: "zāng", meaning: "sujo" },
  "旧": { hanzi: "旧", pinyin: "jiù", meaning: "velho", suggestions: [{"pinyin":"jiu","groupOrder":32,"order":0}] },
  "软": { hanzi: "软", pinyin: "ruǎn", meaning: "macio" },
  "硬": { hanzi: "硬", pinyin: "yìng", meaning: "duro" },
  "滑": { hanzi: "滑", pinyin: "huá", meaning: "escorregadio" },
  "粗": { hanzi: "粗", pinyin: "cū", meaning: "grosso, áspero" },
  "细": { hanzi: "细", pinyin: "xì", meaning: "fino, detalhado" },
  "甜": { hanzi: "甜", pinyin: "tián", meaning: "doce", suggestions: [{"pinyin":"tian","groupOrder":50,"order":1}] },
  "苦": { hanzi: "苦", pinyin: "kǔ", meaning: "amargo" },
  "酸_2": { hanzi: "酸", pinyin: "suān", meaning: "azedo" },
  "咸": { hanzi: "咸", pinyin: "xián", meaning: "salgado" },
  "淡": { hanzi: "淡", pinyin: "dàn", meaning: "sem gosto, leve" },
  "臭_2": { hanzi: "臭", pinyin: "chòu", meaning: "fedorento" },
  "城": { hanzi: "城", pinyin: "chéng", meaning: "cidade" },
  "市": { hanzi: "市", pinyin: "shì", meaning: "cidade, mercado" },
  "镇": { hanzi: "镇", pinyin: "zhèn", meaning: "cidade pequena" },
  "村": { hanzi: "村", pinyin: "cūn", meaning: "vila" },
  "店": { hanzi: "店", pinyin: "diàn", meaning: "loja" },
  "馆": { hanzi: "馆", pinyin: "guǎn", meaning: "edifício público" },
  "场": { hanzi: "场", pinyin: "chǎng", meaning: "campo, local" },
  "楼": { hanzi: "楼", pinyin: "lóu", meaning: "edifício" },
  "房": { hanzi: "房", pinyin: "fáng", meaning: "quarto, casa" },
  "室": { hanzi: "室", pinyin: "shì", meaning: "quarto" },
  "厅": { hanzi: "厅", pinyin: "tīng", meaning: "sala" },
  "堂": { hanzi: "堂", pinyin: "táng", meaning: "salão" },
  "屋": { hanzi: "屋", pinyin: "wū", meaning: "casa, quarto" },
  "桥": { hanzi: "桥", pinyin: "qiáo", meaning: "ponte" },
  "塔": { hanzi: "塔", pinyin: "tǎ", meaning: "torre, pagode" },
  "墙": { hanzi: "墙", pinyin: "qiáng", meaning: "parede" },
  "窗": { hanzi: "窗", pinyin: "chuāng", meaning: "janela" },
  "园": { hanzi: "园", pinyin: "yuán", meaning: "jardim, parque" },
  "林_2": { hanzi: "林", pinyin: "lín", meaning: "floresta" },
  "森": { hanzi: "森", pinyin: "sēn", meaning: "floresta densa" },
  "山_2": { hanzi: "山", pinyin: "shān", meaning: "montanha" },
  "江": { hanzi: "江", pinyin: "jiāng", meaning: "rio (grande)" },
  "海": { hanzi: "海", pinyin: "hǎi", meaning: "mar" },
  "湖": { hanzi: "湖", pinyin: "hú", meaning: "lago" },
  "池": { hanzi: "池", pinyin: "chí", meaning: "lago, piscina" },
  "岛": { hanzi: "岛", pinyin: "dǎo", meaning: "ilha" },
  "洲": { hanzi: "洲", pinyin: "zhōu", meaning: "continente" },
  "洋": { hanzi: "洋", pinyin: "yáng", meaning: "oceano" },
  "滩": { hanzi: "滩", pinyin: "tān", meaning: "praia, banco de areia" },
  "港": { hanzi: "港", pinyin: "gǎng", meaning: "porto" },
  "湾": { hanzi: "湾", pinyin: "wān", meaning: "baía" },
  "师_2": { hanzi: "师", pinyin: "shī", meaning: "professor, mestre" },
  "生_2": { hanzi: "生", pinyin: "shēng", meaning: "estudante, vida" },
  "医": { hanzi: "医", pinyin: "yī", meaning: "médico, medicina" },
  "护_2": { hanzi: "护", pinyin: "hù", meaning: "enfermeiro, proteger" },
  "士": { hanzi: "士", pinyin: "shì", meaning: "soldado, estudioso" },
  "工_3": { hanzi: "工", pinyin: "gōng", meaning: "trabalhador" },
  "农": { hanzi: "农", pinyin: "nóng", meaning: "agricultor" },
  "商": { hanzi: "商", pinyin: "shāng", meaning: "comerciante" },
  "兵": { hanzi: "兵", pinyin: "bīng", meaning: "soldado" },
  "警": { hanzi: "警", pinyin: "jǐng", meaning: "polícia, alertar" },
  "官": { hanzi: "官", pinyin: "guān", meaning: "oficial" },
  "员": { hanzi: "员", pinyin: "yuán", meaning: "membro, funcionário" },
  "长_3": { hanzi: "长", pinyin: "zhǎng", meaning: "chefe, crescer" },
  "理_2": { hanzi: "理", pinyin: "lǐ", meaning: "gerente, razão" },
  "导": { hanzi: "导", pinyin: "dǎo", meaning: "guia, diretor" },
  "演_2": { hanzi: "演", pinyin: "yǎn", meaning: "ator,演出" },
  "唱_2": { hanzi: "唱", pinyin: "chàng", meaning: "cantor" },
  "画": { hanzi: "画", pinyin: "huà", meaning: "pintor, desenhar" },
  "写_2": { hanzi: "写", pinyin: "xiě", meaning: "escritor" },
  "记_2": { hanzi: "记", pinyin: "jì", meaning: "repórter, anotar" },
  "厨": { hanzi: "厨", pinyin: "chú", meaning: "cozinheiro, cozinha" },
  "司_2": { hanzi: "司", pinyin: "sī", meaning: "motorista, departamento" },
  "机": { hanzi: "机", pinyin: "jī", meaning: "piloto, máquina" },
  "售": { hanzi: "售", pinyin: "shòu", meaning: "vendedor" },
  "务": { hanzi: "务", pinyin: "wù", meaning: "garçom, assunto" },
  "今": { hanzi: "今", pinyin: "jīn", meaning: "hoje, agora" },
  "昨": { hanzi: "昨", pinyin: "zuó", meaning: "ontem" },
  "明_3": { hanzi: "明", pinyin: "míng", meaning: "amanhã, brilhante" },
  "早_2": { hanzi: "早", pinyin: "zǎo", meaning: "manhã, cedo" },
  "晚_2": { hanzi: "晚", pinyin: "wǎn", meaning: "noite, tarde" },
  "午": { hanzi: "午", pinyin: "wǔ", meaning: "meio-dia", suggestions: [{"pinyin":"wu","groupOrder":45,"order":1}] },
  "夜": { hanzi: "夜", pinyin: "yè", meaning: "noite" },
  "晨": { hanzi: "晨", pinyin: "chén", meaning: "manhã" },
  "暮": { hanzi: "暮", pinyin: "mù", meaning: "entardecer" },
  "昼": { hanzi: "昼", pinyin: "zhòu", meaning: "dia" },
  "刻": { hanzi: "刻", pinyin: "kè", meaning: "quarto de hora" },
  "钟": { hanzi: "钟", pinyin: "zhōng", meaning: "relógio, sino" },
  "秒": { hanzi: "秒", pinyin: "miǎo", meaning: "segundo" },
  "周": { hanzi: "周", pinyin: "zhōu", meaning: "semana" },
  "季": { hanzi: "季", pinyin: "jì", meaning: "estação, trimestre" },
  "春": { hanzi: "春", pinyin: "chūn", meaning: "primavera" },
  "夏": { hanzi: "夏", pinyin: "xià", meaning: "verão", suggestions: [{"pinyin":"xia","groupOrder":11,"order":1}] },
  "秋": { hanzi: "秋", pinyin: "qiū", meaning: "outono" },
  "冬": { hanzi: "冬", pinyin: "dōng", meaning: "inverno" },
  "节": { hanzi: "节", pinyin: "jié", meaning: "festival, nó" },
  "假_2": { hanzi: "假", pinyin: "jià", meaning: "feriado, férias" },
  "期": { hanzi: "期", pinyin: "qī", meaning: "período", suggestions: [{"pinyin":"qi","groupOrder":47,"order":2}] },
  "段_2": { hanzi: "段", pinyin: "duàn", meaning: "seção, período" },
  "际": { hanzi: "际", pinyin: "jì", meaning: "ocasião, internacional" },
  "天_2": { hanzi: "天", pinyin: "tiān", meaning: "céu, clima" },
  "气_2": { hanzi: "气", pinyin: "qì", meaning: "ar, clima" },
  "候": { hanzi: "候", pinyin: "hòu", meaning: "clima, aguardar" },
  "晴": { hanzi: "晴", pinyin: "qíng", meaning: "ensolarado" },
  "阴": { hanzi: "阴", pinyin: "yīn", meaning: "nublado, sombrio" },
  "云": { hanzi: "云", pinyin: "yún", meaning: "nuvem" },
  "雨": { hanzi: "雨", pinyin: "yǔ", meaning: "chuva" },
  "雪": { hanzi: "雪", pinyin: "xuě", meaning: "neve", suggestions: [{"pinyin":"xue","groupOrder":56,"order":1}] },
  "风": { hanzi: "风", pinyin: "fēng", meaning: "vento" },
  "雷": { hanzi: "雷", pinyin: "léi", meaning: "trovão" },
  "电_2": { hanzi: "电", pinyin: "diàn", meaning: "relâmpago, eletricidade" },
  "雾": { hanzi: "雾", pinyin: "wù", meaning: "neblina" },
  "霜": { hanzi: "霜", pinyin: "shuāng", meaning: "geada" },
  "冰": { hanzi: "冰", pinyin: "bīng", meaning: "gelo" },
  "霞": { hanzi: "霞", pinyin: "xiá", meaning: "brilho do sol" },
  "虹": { hanzi: "虹", pinyin: "hóng", meaning: "arco-íris" },
  "温": { hanzi: "温", pinyin: "wēn", meaning: "temperatura, morno" },
  "度": { hanzi: "度", pinyin: "dù", meaning: "grau, medida" },
  "泥": { hanzi: "泥", pinyin: "ní", meaning: "lama", suggestions: [{"pinyin":"ni","groupOrder":0,"order":1}] },
  "尼": { hanzi: "尼", pinyin: "ní", meaning: "freira", suggestions: [{"pinyin":"ni","groupOrder":0,"order":2}] },
  "好_3": { hanzi: "好", pinyin: "hǎo", meaning: "bom", suggestions: [{"pinyin":"hao","groupOrder":1,"order":0}] },
  "号_2": { hanzi: "号", pinyin: "hào", meaning: "número", suggestions: [{"pinyin":"hao","groupOrder":1,"order":1}] },
  "豪": { hanzi: "豪", pinyin: "háo", meaning: "grandioso", suggestions: [{"pinyin":"hao","groupOrder":1,"order":2}] },
  "握_2": { hanzi: "握", pinyin: "wò", meaning: "segurar", suggestions: [{"pinyin":"wo","groupOrder":2,"order":1}] },
  "事_2": { hanzi: "事", pinyin: "shì", meaning: "assunto", suggestions: [{"pinyin":"shi","groupOrder":3,"order":3}] },
  "得_2": { hanzi: "得", pinyin: "dé", meaning: "obter", suggestions: [{"pinyin":"de","groupOrder":5,"order":1}] },
  "它": { hanzi: "它", pinyin: "tā", meaning: "isso", suggestions: [{"pinyin":"ta","groupOrder":6,"order":2}] },
  "们_3": { hanzi: "们", pinyin: "men", meaning: "plural", suggestions: [{"pinyin":"men","groupOrder":7,"order":0}] },
  "着": { hanzi: "着", pinyin: "zhe", meaning: "partícula aspectual", suggestions: [{"pinyin":"zhe","groupOrder":8,"order":1}] },
  "商_2": { hanzi: "商", pinyin: "shāng", meaning: "comércio", suggestions: [{"pinyin":"shang","groupOrder":10,"order":1}] },
  "区": { hanzi: "区", pinyin: "qū", meaning: "distrito", suggestions: [{"pinyin":"qu","groupOrder":13,"order":1}] },
  "会_3": { hanzi: "会", pinyin: "huì", meaning: "saber/poder", suggestions: [{"pinyin":"hui","groupOrder":14,"order":0}] },
  "回": { hanzi: "回", pinyin: "huí", meaning: "voltar", suggestions: [{"pinyin":"hui","groupOrder":14,"order":1}] },
  "向": { hanzi: "向", pinyin: "xiàng", meaning: "direção", suggestions: [{"pinyin":"xiang","groupOrder":16,"order":1}] },
  "看_2": { hanzi: "看", pinyin: "kàn", meaning: "ver", suggestions: [{"pinyin":"kan","groupOrder":17,"order":0}] },
  "点": { hanzi: "点", pinyin: "diǎn", meaning: "ponto", suggestions: [{"pinyin":"dian","groupOrder":18,"order":0}] },
  "尺": { hanzi: "尺", pinyin: "chǐ", meaning: "régua", suggestions: [{"pinyin":"chi","groupOrder":19,"order":1}] },
  "左": { hanzi: "左", pinyin: "zuǒ", meaning: "esquerda", suggestions: [{"pinyin":"zuo","groupOrder":21,"order":2}] },
  "右": { hanzi: "右", pinyin: "yòu", meaning: "direita", suggestions: [{"pinyin":"you","groupOrder":22,"order":1}] },
  "每_2": { hanzi: "每", pinyin: "měi", meaning: "cada", suggestions: [{"pinyin":"mei","groupOrder":23,"order":1}] },
  "美": { hanzi: "美", pinyin: "měi", meaning: "bonito", suggestions: [{"pinyin":"mei","groupOrder":23,"order":2}] },
  "谁_2": { hanzi: "谁", pinyin: "shéi", meaning: "quem", suggestions: [{"pinyin":"shei","groupOrder":24,"order":0}] },
  "什么": { hanzi: "什么", pinyin: "shénme", meaning: "o quê", suggestions: [{"pinyin":"shenme","groupOrder":25,"order":0}] },
  "哪里": { hanzi: "哪里", pinyin: "nǎlǐ", meaning: "onde", suggestions: [{"pinyin":"nali","groupOrder":26,"order":0}] },
  "朵_2": { hanzi: "朵", pinyin: "duǒ", meaning: "classificador de flores", suggestions: [{"pinyin":"duo","groupOrder":27,"order":1}] },
  "绍": { hanzi: "绍", pinyin: "shào", meaning: "introduzir", suggestions: [{"pinyin":"shao","groupOrder":28,"order":1}] },
  "打_3": { hanzi: "打", pinyin: "dǎ", meaning: "bater", suggestions: [{"pinyin":"da","groupOrder":29,"order":1}] },
  "酒_2": { hanzi: "酒", pinyin: "jiǔ", meaning: "vinho", suggestions: [{"pinyin":"jiu","groupOrder":32,"order":2}] },
  "告": { hanzi: "告", pinyin: "gào", meaning: "dizer", suggestions: [{"pinyin":"gao","groupOrder":33,"order":1}] },
  "常": { hanzi: "常", pinyin: "cháng", meaning: "frequente", suggestions: [{"pinyin":"chang","groupOrder":34,"order":1}] },
  "洪": { hanzi: "洪", pinyin: "hóng", meaning: "inundação", suggestions: [{"pinyin":"hong","groupOrder":37,"order":1}] },
  "懒": { hanzi: "懒", pinyin: "lǎn", meaning: "preguiçoso", suggestions: [{"pinyin":"lan","groupOrder":38,"order":1}] },
  "医_2": { hanzi: "医", pinyin: "yī", meaning: "médico", suggestions: [{"pinyin":"yi","groupOrder":41,"order":1}] },
  "死": { hanzi: "死", pinyin: "sǐ", meaning: "morte", suggestions: [{"pinyin":"si","groupOrder":44,"order":1}] },
  "无_2": { hanzi: "无", pinyin: "wú", meaning: "nenhum", suggestions: [{"pinyin":"wu","groupOrder":45,"order":2}] },
  "把_2": { hanzi: "把", pinyin: "bǎ", meaning: "classificador", suggestions: [{"pinyin":"ba","groupOrder":48,"order":1}] },
  "天_3": { hanzi: "天", pinyin: "tiān", meaning: "céu/dia", suggestions: [{"pinyin":"tian","groupOrder":50,"order":0}] },
  "念": { hanzi: "念", pinyin: "niàn", meaning: "ler em voz alta", suggestions: [{"pinyin":"nian","groupOrder":51,"order":1}] },
  "月_2": { hanzi: "月", pinyin: "yuè", meaning: "mês/lua", suggestions: [{"pinyin":"yue","groupOrder":52,"order":0}] },
  "乐": { hanzi: "乐", pinyin: "lè", meaning: "feliz", suggestions: [{"pinyin":"yue","groupOrder":52,"order":1}] },
  "日_2": { hanzi: "日", pinyin: "rì", meaning: "sol/dia", suggestions: [{"pinyin":"ri","groupOrder":53,"order":0}] },
  "星": { hanzi: "星", pinyin: "xīng", meaning: "estrela", suggestions: [{"pinyin":"xing","groupOrder":54,"order":0}] },
  "行_3": { hanzi: "行", pinyin: "xíng", meaning: "ir/andar", suggestions: [{"pinyin":"xing","groupOrder":54,"order":1}] },
  "家_3": { hanzi: "家", pinyin: "jiā", meaning: "casa/família", suggestions: [{"pinyin":"jia","groupOrder":55,"order":0}] },
  "加": { hanzi: "加", pinyin: "jiā", meaning: "adicionar", suggestions: [{"pinyin":"jia","groupOrder":55,"order":1}] },
  "生_3": { hanzi: "生", pinyin: "shēng", meaning: "nascer/vida", suggestions: [{"pinyin":"sheng","groupOrder":57,"order":0}] },
  "声": { hanzi: "声", pinyin: "shēng", meaning: "som", suggestions: [{"pinyin":"sheng","groupOrder":57,"order":1}] },
  "牢": { hanzi: "牢", pinyin: "láo", meaning: "prisão", suggestions: [{"pinyin":"lao","groupOrder":58,"order":1}] },
  "朋_2": { hanzi: "朋", pinyin: "péng", meaning: "amigo", suggestions: [{"pinyin":"peng","groupOrder":59,"order":0}] },
  "男_2": { hanzi: "男", pinyin: "nán", meaning: "masculino", suggestions: [{"pinyin":"nan","groupOrder":60,"order":0}] },
  "南": { hanzi: "南", pinyin: "nán", meaning: "sul", suggestions: [{"pinyin":"nan","groupOrder":60,"order":1}] },
  "难": { hanzi: "难", pinyin: "nán", meaning: "difícil", suggestions: [{"pinyin":"nan","groupOrder":60,"order":2}] },
  "女_3": { hanzi: "女", pinyin: "nǚ", meaning: "feminino", suggestions: [{"pinyin":"nv","groupOrder":61,"order":0}] },
  "子_3": { hanzi: "子", pinyin: "zǐ", meaning: "filho", suggestions: [{"pinyin":"zi","groupOrder":62,"order":0}] },
  "字_2": { hanzi: "字", pinyin: "zì", meaning: "caractere", suggestions: [{"pinyin":"zi","groupOrder":62,"order":1}] },
  "树": { hanzi: "树", pinyin: "shù", meaning: "árvore", suggestions: [{"pinyin":"shu","groupOrder":63,"order":1}] },
  "数_2": { hanzi: "数", pinyin: "shù", meaning: "número", suggestions: [{"pinyin":"shu","groupOrder":63,"order":2}] },
  "再": { hanzi: "再", pinyin: "zài", meaning: "de novo", suggestions: [{"pinyin":"zai","groupOrder":64,"order":1}] },
  "公_2": { hanzi: "公", pinyin: "gōng", meaning: "público", suggestions: [{"pinyin":"gong","groupOrder":65,"order":1}] },
  "明_4": { hanzi: "明", pinyin: "míng", meaning: "brilhante", suggestions: [{"pinyin":"ming","groupOrder":66,"order":1}] },
  "都_2": { hanzi: "都", pinyin: "dōu", meaning: "todo/ambos", suggestions: [{"pinyin":"dou","groupOrder":67,"order":0}] },
  "能_2": { hanzi: "能", pinyin: "néng", meaning: "poder/capaz", suggestions: [{"pinyin":"neng","groupOrder":68,"order":0}] },
  "要_2": { hanzi: "要", pinyin: "yào", meaning: "querer", suggestions: [{"pinyin":"yao","groupOrder":69,"order":0}] },
  "药": { hanzi: "药", pinyin: "yào", meaning: "remédio", suggestions: [{"pinyin":"yao","groupOrder":69,"order":1}] },
  "今_2": { hanzi: "今", pinyin: "jīn", meaning: "hoje", suggestions: [{"pinyin":"jin","groupOrder":70,"order":0}] },
  "金_2": { hanzi: "金", pinyin: "jīn", meaning: "ouro", suggestions: [{"pinyin":"jin","groupOrder":70,"order":1}] },
  "文_3": { hanzi: "文", pinyin: "wén", meaning: "texto/cultura", suggestions: [{"pinyin":"wen","groupOrder":72,"order":1}] },
  "之": { hanzi: "之", pinyin: "zhī", meaning: "partícula possessiva", suggestions: [{"pinyin":"zhi","groupOrder":73,"order":1}] },
  "道_2": { hanzi: "道", pinyin: "dào", meaning: "caminho", suggestions: [{"pinyin":"dao","groupOrder":74,"order":0}] },
} satisfies Record<string, HanziSourceEntry>

type HanziEntryId = keyof typeof HANZI_ENTRIES_BY_ID
const HANZI_SOURCE_ENTRIES = Object.values(HANZI_ENTRIES_BY_ID) as HanziSourceEntry[]

function toHanziEntry(entry: HanziSourceEntry): HanziEntry {
  return { hanzi: entry.hanzi, pinyin: entry.pinyin, meaning: entry.meaning }
}

function entriesById(...ids: HanziEntryId[]): HanziEntry[] {
  return ids.map((id) => toHanziEntry(HANZI_ENTRIES_BY_ID[id]))
}

export const HANZI_CATALOG = {
  "aulas": entriesById(
    "一", "二", "三", "四", "五", "六", "七", "八",
    "九", "十", "人", "大", "口", "中", "小", "上",
    "下", "国", "学", "习", "汉", "语", "文", "写",
    "字", "女", "子", "好", "水", "门", "王", "日",
    "月", "木", "马", "田", "天", "明", "林", "休",
    "男", "妈", "河", "们", "问", "您", "贵", "姓",
    "我", "是", "呢", "吗", "不", "他", "她", "你",
    "老", "师", "什", "么", "名", "叫", "哪", "说",
    "也", "都", "只", "还是", "很", "高", "兴", "认",
    "识", "在", "工", "作", "司", "进", "出", "系",
    "可", "以", "电", "打", "话", "和", "号", "码",
    "零", "发", "邮", "件", "给", "院", "怎", "样",
    "漂", "亮", "喜", "这", "朋", "友", "请", "坐",
    "谢", "喝", "茶", "儿", "里", "欢", "那",
  ),
  "licao3": entriesById(
    "地方", "个", "这儿", "家", "有", "几", "口_2", "爸爸",
    "妈妈", "和_2", "太太", "孩子", "男孩儿", "女孩儿", "多大", "两",
    "岁", "可爱", "吧", "学校", "多少", "学生", "想", "大概",
    "万", "没有", "多", "千", "去", "为什么", "为", "分公司",
    "老板", "让", "那儿", "百", "少", "因为",
  ),
  "licao4": entriesById(
    "地图", "张", "中文", "葡萄牙文", "看", "一下", "行", "要",
    "给_2", "干", "是的", "玩儿", "知道", "比较", "真", "有意思",
    "意思", "龙", "山", "词典", "汉葡词典", "葡汉词典", "本", "谁",
    "请问", "问", "对", "非常", "有用", "能", "用", "当然",
    "书", "本子", "笔", "支", "教室", "上课",
  ),
  "licao5": entriesById(
    "小姐", "会", "一点儿", "先生", "买", "件_2", "衬衫", "白",
    "钱", "块", "太", "贵_2", "红", "便宜", "还", "条",
    "裤子", "试", "那_2", "来", "饭店", "最", "好吃", "菜",
    "糖醋鱼", "糖", "醋", "鱼", "吃", "辣", "酸辣汤", "酸",
    "汤", "牛肉", "牛", "肉", "红烧", "米饭", "水饺", "瓶",
    "啤酒", "等", "东西", "买东西", "商店", "卖", "衣服",
  ),
  "hsk1": entriesById(
    "你_2", "好_2", "我", "是_2", "的", "了", "不_2", "在_2",
    "人", "有_2", "他", "这", "中_2", "大", "来", "上_2",
    "国", "个_2", "到", "说_2", "们_2", "为_2", "子_2", "和_3",
    "地", "出", "道", "也", "时", "年", "得", "就",
    "那", "要", "下_2", "以_2", "生", "会_2", "天", "过",
    "能", "她", "多", "去", "做", "想_2", "看", "几_2",
    "吗_2", "呢_2", "吧_2", "啊", "叫_2", "喜", "欢", "爱",
    "买", "卖", "吃", "喝",
  ),
  "hsk2": entriesById(
    "对_2", "自", "事", "起", "还_2", "用", "家_2", "方",
    "开", "手", "水", "小", "从", "现", "己", "者",
    "月", "把", "见", "第", "问", "长", "日", "最_2",
    "分", "前", "外", "定", "给_3", "名", "成", "学",
    "当", "体", "样", "新", "知", "作", "等_2", "老_2",
    "听", "读", "写", "话_2", "住", "路", "走", "跑",
    "站", "坐", "睡", "觉", "穿", "衣", "服", "鞋",
    "帽", "眼", "睛", "耳", "朵", "口_3", "鼻", "头",
    "脸", "脚", "腿",
  ),
  "hsk3": entriesById(
    "才", "民", "文_2", "理", "发_2", "气", "动", "意",
    "心", "面", "力", "高", "本_2", "经", "门", "工_2",
    "然", "没", "间", "行_2", "相", "因", "同", "三",
    "已", "两", "些", "无", "认_2", "识_2", "觉_2", "记",
    "忘", "懂", "比", "较", "更", "特", "别", "其",
    "实", "真_2", "假", "错", "完", "始", "终", "结",
    "束", "决", "选", "择", "改", "变", "化", "需",
    "必", "须", "该", "应",
  ),
  "hsk4": entriesById(
    "而", "且", "况", "若", "虽", "尽", "管", "除",
    "非", "否", "另", "各", "每", "任", "何", "某",
    "整", "般", "普", "遍", "共", "总", "另", "互",
    "彼", "此", "双", "单", "独", "孤", "众", "群",
    "集", "合", "联", "接", "系_2", "关", "键", "钥",
    "匙", "锁", "闭", "启", "推", "拉", "抬", "举",
    "放", "置", "摆", "排", "列", "序", "次", "级",
    "层", "段", "落",
  ),
  "hsk5": entriesById(
    "版", "报", "杂", "志", "刊", "登", "载", "印",
    "刷", "编", "译", "著", "述", "论", "议", "评",
    "价", "值", "费", "花", "钱", "币", "元", "块_2",
    "角", "毛", "富", "贫", "穷", "贵_3", "廉", "宜",
    "赚", "挣", "赔", "亏", "损", "失", "丢", "遗",
    "留", "存", "保", "护", "守", "卫", "防", "备",
    "预", "测", "算", "数", "计", "划", "案", "略",
    "策", "谋", "虑",
  ),
  "hsk6": entriesById(
    "哲", "慧", "智", "愚", "蠢", "聪", "敏", "钝",
    "伶", "俐", "巧", "拙", "笨", "呆", "傻", "疯",
    "狂", "癫", "痴", "迷", "惑", "糊", "涂", "抹",
    "擦", "刮", "削", "割", "砍", "劈", "裂", "碎",
    "破", "损_2", "坏", "烂", "腐", "朽", "蚀", "锈",
    "霉", "臭", "香", "芳", "馨", "芬", "馥", "郁",
    "闷", "沉", "浮", "漂_2", "泛", "溢", "洒", "泼",
    "喷", "洒_2", "淋",
  ),
  "numbers": entriesById(
    "一", "二", "三", "四", "五", "六", "七", "八",
    "九", "十", "百_2", "千", "万", "零_2", "两_2", "半",
    "双_2",
  ),
  "colors": entriesById(
    "红", "黄", "蓝", "绿", "白", "黑", "灰", "紫",
    "橙", "粉", "棕", "褐", "金", "银", "青",
  ),
  "family": entriesById(
    "爸", "妈_2", "哥", "姐", "弟", "妹", "儿_2", "女_2",
    "孩", "祖", "爷", "奶", "公", "婆", "夫", "妻",
    "叔", "伯", "姨", "姑", "舅", "侄", "甥", "孙",
  ),
  "food": entriesById(
    "饭", "菜_2", "肉", "鱼", "鸡", "蛋", "茶", "咖",
    "啡", "奶_2", "果", "汤_2", "面_2", "包", "酒", "糖",
    "盐", "醋", "油", "酱", "豆", "腐_2", "米", "粉_2",
    "饺", "馒", "头_2", "饼", "糕", "粥", "虾", "蟹",
    "贝", "鸭", "鹅",
  ),
  "animals": entriesById(
    "猫", "狗", "鸟", "马", "牛_2", "羊", "猪", "虎",
    "龙", "蛇", "兔", "鼠", "狼", "熊", "豹", "狮",
    "象", "猴", "鹿", "鹰", "鸽", "鸡_2", "鸭", "鹅",
    "蚁", "蜂", "蝶", "蝴", "蜘", "蛛",
  ),
  "verbs": entriesById(
    "跑", "跳", "飞", "游", "爬", "推", "拉", "扔",
    "丢_2", "捡", "抓", "握", "抱", "摸", "碰", "���",
    "打_2", "踢", "扔", "投", "掷", "扔", "喊", "叫_3",
    "哭", "笑", "唱", "跳_2", "舞", "演", "奏", "弹",
    "拉_2", "吹", "敲",
  ),
  "adjectives": entriesById(
    "大", "小", "长_2", "短", "高", "低", "厚", "薄",
    "宽", "窄", "深", "浅", "重", "轻", "快", "慢",
    "早", "晚", "热", "冷", "暖", "凉", "干_2", "湿",
    "亮_2", "暗", "明_2", "亮_3", "净", "脏", "新", "旧",
    "软", "硬", "滑", "粗", "细", "甜", "苦", "酸_2",
    "辣", "咸", "淡", "香", "臭_2",
  ),
  "places": entriesById(
    "城", "市", "镇", "村", "店", "馆", "场", "院",
    "楼", "房", "室", "厅", "堂", "屋", "桥", "塔",
    "墙", "窗", "园", "林_2", "森", "山_2", "河", "江",
    "海", "湖", "池", "岛", "洲", "洋", "滩", "港",
    "湾",
  ),
  "professions": entriesById(
    "师_2", "生_2", "医", "护_2", "士", "工_3", "农", "商",
    "兵", "警", "官", "员", "长_3", "理_2", "导", "演_2",
    "唱_2", "画", "写_2", "记_2", "厨", "司_2", "机", "售",
    "务",
  ),
  "time": entriesById(
    "今", "昨", "明_3", "早_2", "晚_2", "午", "夜", "晨",
    "暮", "昼", "刻", "钟", "秒", "周", "季", "春",
    "夏", "秋", "冬", "节", "假_2", "期", "段_2", "际",
  ),
  "weather": entriesById(
    "天_2", "气_2", "候", "晴", "阴", "云", "雨", "雪",
    "风", "雷", "电_2", "雾", "霜", "冰", "霞", "虹",
    "温", "度",
  ),
}

export const HANZI_ENTRIES: HanziEntry[] = HANZI_SOURCE_ENTRIES.map(toHanziEntry)

export const PINYIN_TO_HANZI: Record<string, HanziEntry[]> = Object.fromEntries(
  HANZI_SOURCE_ENTRIES
    .flatMap((entry) =>
      (entry.suggestions ?? []).map((suggestion) => ({ entry, suggestion })),
    )
    .sort(
      (left, right) =>
        left.suggestion.groupOrder - right.suggestion.groupOrder || left.suggestion.order - right.suggestion.order,
    )
    .reduce<Array<[string, HanziEntry[]]>>((groups, { entry, suggestion }) => {
      const currentGroup = groups.at(-1)
      if (currentGroup?.[0] === suggestion.pinyin) {
        currentGroup[1].push(toHanziEntry(entry))
      } else {
        groups.push([suggestion.pinyin, [toHanziEntry(entry)]])
      }
      return groups
    }, []),
)
